const $=s=>document.querySelector(s),viewer=$('#viewer');
const notes={
  defenders:['Three block-proportioned defenders and three fortifications. Armor, grips, pivots and bold silhouettes carry the shared direction.','Roblox character and tower concepts; current animated demo units are shown below.'],
  rainbow:['Cobalt enamel · ochre crown brackets · mint glass eye · stitched violet wraps.','Plasma carbine / royal blade / crown ember staff.'],
  doors:['Oxblood wood · aged brass hardware · teal keyhole lens · dark leather.','Plasma carbine / latch blade / lantern ember staff.'],
  tide:['Sea-jade enamel · ivory ceramic · coral spiral cores · braided rope.','Plasma carbine / tidal cutlass / spiral ember staff.'],
  interface:['Roblox-focused HUD and loadout: readable wave objective, five-slot hotbar, touch actions and illustrated equipment cards.','Concept art. This proposes the future interface; it does not replace the demo HUD.']
};
let plates=[],active=0,opener=null,filter='all',model=0;
function openPlate(id,button){const index=plates.findIndex(p=>p.id===id);if(index<0)return;active=index;opener=button||opener;const p=plates[active];$('#viewer-title').textContent=p.title;$('#full-image').src='lib/artboard/'+p.file;$('#full-image').alt=p.title;$('#download').href='lib/artboard/'+p.file;$('#plate-number').textContent=(active+1)+' / '+plates.length;$('.image-scroll').classList.remove('zoomed');if(!viewer.open)viewer.showModal();}
function update(){const manufacturer=$('#manufacturer').value;let shown=0;for(const p of plates){if(p.id==='frontier')continue;const visible=(filter==='all'||p.category===filter)&&(manufacturer==='all'||p.id===manufacturer);document.getElementById('plate-'+p.id).hidden=!visible;if(visible)shown++;}$('#count').textContent=shown+' concept '+(shown===1?'plate':'plates')+' · select an image to inspect and download';}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$('#manufacturer').value='all';document.querySelectorAll('[data-filter]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));update();});
$('#manufacturer').onchange=()=>{filter=$('#manufacturer').value==='all'?'all':'weapons';document.querySelectorAll('[data-filter]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.filter===filter)));update();};
$('#close-viewer').onclick=()=>viewer.close();viewer.addEventListener('close',()=>opener?.focus());$('#previous').onclick=()=>openPlate(plates[(active+plates.length-1)%plates.length].id);$('#next').onclick=()=>openPlate(plates[(active+1)%plates.length].id);$('#full-image').onclick=()=>$('.image-scroll').classList.toggle('zoomed');viewer.addEventListener('keydown',e=>{if(e.code==='ArrowLeft')$('#previous').click();if(e.code==='ArrowRight')$('#next').click();});viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close();});
function loadModels(){let frame=$('#live-models');if(!frame){frame=document.createElement('iframe');frame.id='live-models';frame.title='Live Worldheart asset, animation and effects stage';frame.allow='fullscreen';$('#viewer-shell').replaceChildren(frame);frame.src='asset-stage.html?preset=vivid&asset='+model;return;}const stage=frame.contentWindow?.INK_STAGE;if(stage){if(model===0){frame.contentWindow.document.querySelector('#overview').click();}else stage.select(model,true);}else frame.src='asset-stage.html?preset=vivid&asset='+model;}
$('#load-models').onclick=loadModels;document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{model=Number(b.dataset.model);document.querySelectorAll('[data-model]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));loadModels();});
try{
  const response=await fetch('lib/artboard/catalogue.json');if(!response.ok)throw Error('Concept catalogue did not load. Reload to retry.');const catalogue=await response.json();plates=catalogue.plates;
  for(const p of plates.filter(p=>p.id!=='frontier')){const figure=document.createElement('figure');figure.className='plate';figure.id='plate-'+p.id;const index=plates.indexOf(p)+1;
    const top=document.createElement('div');top.className='plate-top';const title=document.createElement('h3');title.textContent=String(index).padStart(2,'0')+' / '+p.title;const tag=document.createElement('span');tag.className='tag';tag.textContent=p.manufacturer?'MANUFACTURER STUDY · '+p.ip.toUpperCase():p.category==='interface'?'ROBLOX UI CONCEPT':'UNITS & TOWERS';top.append(title,tag);
    const button=document.createElement('button');button.setAttribute('aria-label','Inspect '+p.title);const img=document.createElement('img');img.src='lib/artboard/'+p.preview;img.alt=notes[p.id][0];img.width=1536;img.height=1024;img.loading='lazy';button.append(img);button.onclick=()=>openPlate(p.id,button);
    const caption=document.createElement('figcaption');for(const text of notes[p.id]){const para=document.createElement('p');para.textContent=text;caption.append(para);}const link=document.createElement('a');link.href=p.source||'lib/artboard/'+p.file;link.textContent=p.source?p.ip+' reference ↗':'Full-size plate ↗';link.target='_blank';link.rel='noopener';caption.append(link);figure.append(top,button,caption);$('#gallery').append(figure);
  }
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPlate(b.dataset.open,b));update();window.WH_ARTBOARD={catalogue,openPlate,get model(){return model;}};
}catch(error){$('#board-error').textContent=error.message;$('#board-error').hidden=false;$('#count').textContent='Concept catalogue unavailable.';}
