import * as THREE from 'three';
import {GLTFLoader} from '../art-candidates/hard-cel-v1/lib/addons/loaders/GLTFLoader.js';
import {createCandidateMaterials} from './hard-cel-materials.js';
import {VERSIONS} from './hard-cel-versions.js';
import {createPaintedEnvironment} from '../art-candidates/hard-cel-v1/js/painted-environment.js';

const $=s=>document.querySelector(s),panels=[...document.querySelectorAll('.viewport')],reduced=matchMedia('(prefers-reduced-motion: reduce)');
const state={view:'valley',version:'v5',reference:'v1',layout:'pair',light:'golden',ink:true,paint:true,motion:!reduced.matches};
let renderer,paint,environment,ready=false,lost=false,dirty=true,time=0,last=performance.now(),frames=0;
const camera=new THREE.PerspectiveCamera(43,1,.25,180);camera.layers.enable(1);
const scene=new THREE.Scene();scene.background=new THREE.Color('#c8d5cb');scene.fog=new THREE.FogExp2('#c8d5cb',.009);
const light=new THREE.DirectionalLight('#ffe6b8',2.1);light.position.set(-13,24,13);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-30,right:30,top:30,bottom:-30,near:1,far:85});light.shadow.bias=-.0001;light.shadow.normalBias=.035;light.shadow.radius=4;light.shadow.blurSamples=8;scene.add(light);
const hemi=new THREE.HemisphereLight('#e2ebdc','#83765f',1.15);scene.add(hemi);
const fill=new THREE.DirectionalLight('#bdced7',.35);fill.position.set(15,10,-15);scene.add(fill);
const subjects=new Map(),assets=[],timings=[],pointers=new Map();let yaw=.12,pitch=.34,distance=34,target=new THREE.Vector3(0,1.5,0),lastInfo=0;
const views={valley:{target:[0,2.0,-1],distance:29,pitch:.23,yaw:.10},commander:{target:[-3,1.6,4],distance:7.4,pitch:.13,yaw:.36},tower:{target:[-5,1.7,-2],distance:8.5,pitch:.25,yaw:-.35},enemy:{target:[8,1.25,3],distance:7.7,pitch:.18,yaw:.45}};
function reset(){const v=views[state.view];target.set(...v.target);distance=v.distance;pitch=v.pitch;yaw=v.yaw;dirty=true;}
function url(){const q=new URLSearchParams();q.set('version',state.version);q.set('layout',state.layout);if(state.reference!=='v1')q.set('reference',state.reference);if(state.view!=='valley')q.set('view',state.view);if(state.light!=='golden')q.set('light',state.light);history.replaceState(null,'',location.pathname+(q.size?'?'+q:''));}
function setView(view){state.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));reset();url();}
function setLayout(layout){state.layout=state.version===state.reference&&layout==='pair'?'single':layout;$('#layout').value=state.layout;$('#reference').disabled=state.layout!=='pair';$('#stage').className='stage '+state.layout;const ids=state.layout==='all'?['v1','v2','v3',state.version==='v4'?'v4':'v5']:state.layout==='single'?[state.version]:[state.reference,state.version];panels.forEach((panel,i)=>{panel.hidden=i>=ids.length;if(panel.hidden)return;const id=ids[i],v=VERSIONS[id];panel.dataset.version=id;panel.querySelector('.scene-tag').textContent=v.version+' / '+v.name.toUpperCase();panel.querySelector('.scene-note').textContent=v.status;panel.setAttribute('aria-label',v.name+' 3D scene. Drag or arrow keys to orbit, scroll or plus and minus to zoom.');});dirty=true;url();}
function setVersion(version){state.version=version;const v=VERSIONS[version];document.querySelectorAll('[data-version]').forEach(b=>{if(b.tagName==='BUTTON')b.setAttribute('aria-pressed',String(b.dataset.version===version));});$('#version-number').textContent='VERSION '+v.version;$('#version-name').textContent=v.name;$('#version-description').textContent=v.description;$('#version-status').textContent=v.status;setLayout(state.layout);}
function setLight(){const golden=state.light==='golden';light.color.set(golden?'#ffe6b8':'#e7edf2');light.intensity=golden?2.1:1.6;light.position.set(golden?-13:-5,golden?24:30,golden?13:10);hemi.intensity=golden?1.15:1.4;scene.background.set(golden?'#c8d5cb':'#bcc9cc');scene.fog.color.copy(scene.background);dirty=true;url();}
function setMotion(){const b=$('#motion');b.setAttribute('aria-pressed',String(state.motion));b.textContent=state.motion?'Pause breeze':'Play breeze';$('#runtime-status').textContent=state.motion?'Live 3D · breeze on':'Still frame · live 3D';dirty=true;}
function draw(){if(!ready||lost)return;const stage=$('#stage').getBoundingClientRect(),w=Math.round(stage.width),h=Math.round(stage.height),ratio=renderer.getPixelRatio();if(renderer.domElement.width!==Math.round(w*ratio)||renderer.domElement.height!==Math.round(h*ratio))renderer.setSize(w,h,false);
  renderer.setScissorTest(false);renderer.setViewport(0,0,w,h);renderer.clear();renderer.setScissorTest(true);let calls=0,triangles=0;
  for(let i=0;i<panels.length;i++){if(panels[i].hidden)continue;const rect=panels[i].getBoundingClientRect(),pw=Math.round(rect.width),ph=Math.round(rect.height);renderer.setViewport(Math.round(rect.left-stage.left),Math.round(stage.bottom-rect.bottom),pw,ph);renderer.setScissor(Math.round(rect.left-stage.left),Math.round(stage.bottom-rect.bottom),pw,ph);renderer.clear();camera.aspect=pw/ph;camera.updateProjectionMatrix();const fit=Math.max(1,.85/camera.aspect),d=distance*fit;camera.position.set(target.x+Math.sin(yaw)*Math.cos(pitch)*d,target.y+Math.sin(pitch)*d,target.z+Math.cos(yaw)*Math.cos(pitch)*d);camera.lookAt(target);const id=panels[i].dataset.version;paint.setVariant(id,state,pw,ph,scene);light.shadow.radius=VERSIONS[id].shadowRadius;scene.fog.density=VERSIONS[id].fog;renderer.render(scene,camera);calls+=renderer.info.render.calls;triangles+=renderer.info.render.triangles;}
  renderer.setScissorTest(false);dirty=false;frames++;window.CANDIDATE_LAB.metrics={frames,calls,triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,models:assets.length,grassBlades:environment.grassCount,flowers:environment.flowerCount,contexts:1};
}
function frame(now){requestAnimationFrame(frame);if(!ready||document.hidden||lost)return;const elapsed=now-last;last=now;if(state.motion){time+=Math.min(elapsed/1000,1/30);environment.animate(time);dirty=true;if(timings.length<900)timings.push(elapsed);}if(dirty)draw();if(now-lastInfo>1100){$('#runtime-status').textContent=state.motion?'Live 3D · breeze on':'Still frame · live 3D';lastInfo=now;}}
async function loadModels(){const loader=new GLTFLoader();let completed=0;
  const source=await Promise.all(['commander','enemy','tower'].map(async name=>{const gltf=await loader.loadAsync('art-candidates/hard-cel-v1/lib/painted/'+name+'.gltf');completed++;$('#load-status').textContent=`Loaded ${completed} of 3 textured models`;const group=gltf.scene;group.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(group),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const meshes=[];group.traverse(o=>{if(o.isMesh)meshes.push(o);});let vertices=0,triangles=0,textures=0;
    for(const m of meshes){const old=m.material;if(!old.map)throw Error(name+' has no painted texture');old.map.anisotropy=4;old.map.colorSpace=THREE.SRGBColorSpace;const mat=paint.material(old.color.clone(),{map:old.map});m.material=mat;m.castShadow=m.receiveShadow=true;paint.contour(m);textures++;vertices+=m.geometry.attributes.position.count;triangles+=(m.geometry.index?.count||m.geometry.attributes.position.count)/3;}
    assets.push({name,vertices,triangles,textures,sourceDimensions:size.toArray(),rigged:!!gltf.animations.length});return {name,group,bounds,size,center};}));
  function place(name,x,z,tall,rotation=0){const src=source.find(a=>a.name===name),container=new THREE.Group(),model=src.group.clone(true),scale=tall/src.size.y;model.scale.multiplyScalar(scale);model.position.x-=src.center.x*scale;model.position.z-=src.center.z*scale;model.position.y-=src.bounds.min.y*scale;container.add(model);container.position.set(x,environment.height(x,z),z);container.rotation.y=rotation;scene.add(container);model.traverse(m=>{if(m.isMesh&&m.material===paint.shells[0]?.material&&!paint.shells.includes(m))paint.shells.push(m);});return container;}
  subjects.set('commander',place('commander',-3,4,3.1,.2));subjects.set('tower',place('tower',-5,-2,3.6,0.2));place('tower',6,-7,2.8,.9);subjects.set('enemy',place('enemy',8,3,2.65,-.8));
  for(const [name,obj] of subjects){const box=new THREE.Box3().setFromObject(obj);const center=box.getCenter(new THREE.Vector3());views[name].target=center.toArray();}
}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('button[data-version]').forEach(b=>b.addEventListener('click',()=>setVersion(b.dataset.version)));$('#layout').addEventListener('change',e=>setLayout(e.target.value));$('#reference').addEventListener('change',e=>{state.reference=e.target.value;setLayout(state.layout);});$('#reset').addEventListener('click',reset);$('#light').addEventListener('change',e=>{state.light=e.target.value;setLight();});$('#motion').addEventListener('click',()=>{state.motion=!state.motion;setMotion();});
for(const id of ['ink','paint'])$('#'+id).addEventListener('change',e=>{state[id]=e.target.checked;dirty=true;});
$('#export').addEventListener('click',()=>{if(!ready||lost)return;draw();const a=document.createElement('a');a.download='worldheart-hard-cel-'+state.version+'-'+state.layout+'-'+state.view+'.png';a.href=renderer.domElement.toDataURL('image/png');a.click();});
for(const panel of panels){panel.addEventListener('pointerdown',e=>{panel.focus({preventScroll:true});pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});panel.setPointerCapture(e.pointerId);});panel.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(!p)return;yaw-=(e.clientX-p.x)*.006;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-p.y)*.004,.035,1.3);p.x=e.clientX;p.y=e.clientY;dirty=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])panel.addEventListener(type,e=>pointers.delete(e.pointerId));panel.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance*Math.exp(e.deltaY*.001),3,70);dirty=true;},{passive:false});panel.addEventListener('keydown',e=>{let used=true;switch(e.key){case 'ArrowLeft':yaw-=.09;break;case 'ArrowRight':yaw+=.09;break;case 'ArrowUp':pitch=Math.min(1.3,pitch+.06);break;case 'ArrowDown':pitch=Math.max(.035,pitch-.06);break;case '+':case '=':distance=Math.max(3,distance*.9);break;case '-':distance=Math.min(70,distance*1.1);break;case 'Home':reset();break;default:used=false;}if(used){e.preventDefault();dirty=true;}});}
window.addEventListener('blur',()=>pointers.clear());window.addEventListener('resize',()=>{dirty=true;});document.addEventListener('visibilitychange',()=>{last=performance.now();dirty=true;});reduced.addEventListener('change',e=>{if(e.matches){state.motion=false;setMotion();}});
async function boot(){try{
    renderer=new THREE.WebGLRenderer({canvas:$('#painted-view'),antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.VSMShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.autoClear=false;
    paint=await createCandidateMaterials();environment=createPaintedEnvironment(paint);scene.add(environment.root);await loadModels();
    window.CANDIDATE_LAB={state,assets,versions:VERSIONS,metrics:{},get camera(){return {yaw,pitch,distance,target:target.toArray()};},get time(){return time;},get timings(){return timings.slice();},get ready(){return ready;},render:draw};
    const params=new URLSearchParams(location.search);if(views[params.get('view')])state.view=params.get('view');if(params.get('light')==='overcast'){state.light='overcast';$('#light').value='overcast';}if(VERSIONS[params.get('version')])state.version=params.get('version');if(['v1','v4'].includes(params.get('reference'))){state.reference=params.get('reference');$('#reference').value=state.reference;}if(['pair','all','single'].includes(params.get('layout')))state.layout=params.get('layout');setView(state.view);setVersion(state.version);setLight();setMotion();environment.animate(0);ready=true;$('#export').disabled=false;draw();$('#loading').hidden=true;last=performance.now();requestAnimationFrame(frame);
    renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;$('#export').disabled=true;$('#loading').hidden=false;$('#load-status').textContent='Graphics interrupted. Restore the tab or reload to continue.';});renderer.domElement.addEventListener('webglcontextrestored',()=>{lost=false;dirty=true;$('#export').disabled=false;$('#loading').hidden=true;});
  }catch(error){$('#loading strong').textContent='The study could not finish loading';$('#load-status').textContent='Reload to retry. '+error.message;window.CANDIDATE_LAB_ERROR=String(error);console.error(error);}}
boot();
