import * as THREE from 'three';
import {GLTFLoader} from '../art-candidates/hard-cel-v1/lib/addons/loaders/GLTFLoader.js';
import {createSurfaceMaterials as createCandidateMaterials} from './arena-materials.js';
import {VERSIONS} from './hard-cel-versions.js';
import {createPaintedEnvironment} from '../art-candidates/hard-cel-v1/js/painted-environment.js';
import {createActor} from './playground-actor.js';
import {createEffects} from './playground-fx.js';

const $=s=>document.querySelector(s),canvas=$('#world'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const scene=new THREE.Scene();scene.background=new THREE.Color('#c8d5cb');scene.fog=new THREE.FogExp2('#c8d5cb',.009);
const camera=new THREE.PerspectiveCamera(48,1,.15,150);camera.layers.enable(1);
const sun=new THREE.DirectionalLight('#ffe6b8',2.1);sun.position.set(-13,24,13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-28,right:28,top:28,bottom:-28,near:1,far:85});sun.shadow.bias=-.0001;sun.shadow.normalBias=.035;sun.shadow.blurSamples=8;scene.add(sun);
scene.add(new THREE.HemisphereLight('#e2ebdc','#83765f',1.15));const fill=new THREE.DirectionalLight('#bdced7',.35);fill.position.set(15,10,-15);scene.add(fill);
const state={style:new URLSearchParams(location.search).get('style')==='v5'?'v5':'v1',paused:false,ink:true,paint:true,light:'golden',hits:0,strikes:0,pulses:0,jumps:0,contacts:0};
let renderer,paint,env,actor,friend,fx,ready=false,lost=false,time=0,last=performance.now(),yaw=0,pitch=.3,distance=9.5,inputYaw=0,jump=0,vertical=0,cooldown=0,shake=0,dust=0,actionKind='',tower,towerTime=0,shot=null;
const velocity=new THREE.Vector3(),desired=new THREE.Vector3(),follow=new THREE.Vector3(),keys=new Set(),stick={x:0,y:0},targets=[],timings=[],events=[];
const flashColor=new THREE.Color('#ffe4ad'),v=new THREE.Vector3(),up=new THREE.Vector3(0,1,0);let touchRun=false,orbit=null,stickPointer=null,uiTime=0;
const event=(kind,data={})=>{events.push({time,kind,...data});if(events.length>300)events.shift();};
const blocked=(x,z)=>x < -17||x > 17||z < -13||z > 20||targets.some(t=>t.recover<=0&&Math.hypot(x-t.root.position.x,z-t.root.position.z)<1.4)||[[-10,1,2],[13,-7,1.9],[-9,-12,1.7],[14,11,1.6],[-14,-10,4],[-10,-17,4],[18,-11,4],[-20,1,4],[-7,-4,1],[-5.5,-4,1],[-4,-4,1],[-2.5,-4,.9]].some(([a,b,r])=>Math.hypot(x-a,z-b)<r);

function style(id){state.style=id;document.querySelectorAll('[data-style]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.style===id)));$('#scene-status').textContent=VERSIONS[id].name+' '+VERSIONS[id].version+' · live motion study';history.replaceState(null,'',location.pathname+'?style='+id);}
function clearInput(){keys.clear();stick.x=stick.y=0;orbit=null;stickPointer=null;$('#thumb').style.transform='';}
function pause(value){state.paused=value;clearInput();$('#pause').textContent=value?'Resume':'Pause';$('#paused').hidden=!value;last=performance.now();}
function reset(){if(!ready)return;clearInput();touchRun=false;$('#touch-run').setAttribute('aria-pressed','false');velocity.set(0,0,0);actor.root.position.set(0,env.height(0,10),10);actor.root.rotation.y=Math.PI;actor.reset();yaw=0;pitch=.3;distance=9.5;inputYaw=0;jump=vertical=cooldown=shake=dust=0;state.hits=state.strikes=state.pulses=state.jumps=state.contacts=0;time=towerTime=0;shot=null;projectile.visible=false;fx.clear();targets.forEach(t=>{t.hp=3;t.recoil=t.recover=0;t.root.visible=true;t.root.scale.setScalar(1);t.root.rotation.z=0;});follow.copy(actor.root.position).add(new THREE.Vector3(0,1.5,0));pause(false);$('#hit-status').textContent='Land a strike to see the paint move.';}
function attack(kind){if(!ready||lost||state.paused||jump>.05||actor.locked||(kind==='pulse'&&cooldown>0))return;
  if(actor.action(kind==='pulse'?'Wave':'Punch',kind==='pulse'?.95:.7)){actionKind=kind;if(kind==='pulse'){state.pulses++;cooldown=2.8;}else state.strikes++;event('attack',{attack:kind});}}
function leap(){if(!ready||lost||state.paused||jump>.01||actor.locked)return;if(actor.action('Jump',.85)){vertical=6.6;state.jumps++;actionKind='jump';event('jump');}}
function damage(t,source){if(t.recover>0)return;t.hp--;t.recoil=.42;state.hits++;fx.hit(t.root.position.clone().add(new THREE.Vector3(0,1.25,0)),source==='pulse'?'#a2ebd4':'#f3ca78');if(t.hp<=0){t.recover=2.4;fx.puff(t.root.position.clone().add(new THREE.Vector3(0,.7,0)),{count:24,color:'#aaa993',size:.2,speed:2.3,life:.8});}shake=reduced.matches?0:.13;event('hit',{target:t.name,source,hp:t.hp});$('#hit-status').textContent=t.name+' · '+(t.hp<=0?'reforming in a moment':source==='pulse'?'pulse impact':'clean strike');}
function contact(){if(actionKind==='jump')return;state.contacts++;const p=actor.root.position,forward=new THREE.Vector3(Math.sin(actor.root.rotation.y),0,Math.cos(actor.root.rotation.y));
  if(actionKind==='pulse'){fx.ring(p.clone().add(new THREE.Vector3(0,.5,0)),{radius:5.5,color:'#a8eed3',life:.8});fx.puff(p.clone().add(new THREE.Vector3(0,1,0)),{count:22,color:'#b6edd6',speed:3,gravity:0,up:.8});}
  else{fx.ring(p.clone().addScaledVector(forward,1).add(new THREE.Vector3(0,1.2,0)),{radius:1,color:'#f8d994',life:.2,vertical:true});fx.puff(p.clone().addScaledVector(forward,1.4).add(new THREE.Vector3(0,1.2,0)),{count:5,color:'#fae4b1',speed:1,gravity:0,up:0,life:.2});}
  for(const t of targets){v.copy(t.root.position).sub(p);v.y=0;const d=v.length();if(d<(actionKind==='pulse'?5.5:3.1)&&(actionKind==='pulse'||v.normalize().dot(forward)>.25))damage(t,actionKind);}
}
const projectile=new THREE.Mesh(new THREE.IcosahedronGeometry(.15,1),new THREE.MeshBasicMaterial({color:'#f9d996'}));projectile.visible=false;scene.add(projectile);

async function specimens(){const loader=new GLTFLoader(),sources={};for(const name of ['commander','enemy','tower']){const gltf=await loader.loadAsync('art-candidates/hard-cel-v1/lib/painted/'+name+'.gltf'),model=gltf.scene;model.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(model),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());sources[name]={model,bounds,center,size};}
  function place(name,x,z,height,angle=0){const s=sources[name],root=new THREE.Group(),model=s.model.clone(true),scale=height/s.size.y;model.scale.multiplyScalar(scale);model.position.set(-s.center.x*scale,-s.bounds.min.y*scale,-s.center.z*scale);root.add(model);root.position.set(x,env.height(x,z),z);root.rotation.y=angle;const meshes=[];root.userData.paint=[];model.traverse(o=>{if(o.isMesh)meshes.push(o);});for(const m of meshes){const old=m.material;if(old.map){old.map.colorSpace=THREE.SRGBColorSpace;old.map.anisotropy=4;}m.material=paint.material(old.color.clone(),{map:old.map});root.userData.paint.push({material:m.material,color:m.material.color.clone()});m.castShadow=m.receiveShadow=true;paint.contour(m);}scene.add(root);return root;}
  place('commander',-4,2,3.1,.6);tower=place('tower',-10,8,3.6,.95);tower.userData.baseZ=tower.children[0].position.z;for(const [i,x,z] of [[1,0,5],[2,7,1],[3,-7,12]]){const root=place('enemy',x,z,2.25,Math.PI);targets.push({name:'Training invader '+i,root,hp:3,recoil:0,recover:0});const ring=new THREE.Mesh(new THREE.TorusGeometry(1.3,.045,6,64),new THREE.MeshBasicMaterial({color:'#b4ddba'}));ring.rotation.x=Math.PI/2;ring.position.set(x,env.height(x,z)+.05,z);scene.add(ring);}
}
function step(dt){if(!ready||state.paused||lost)return;dt=Math.max(0,Math.min(dt,.05));if(!dt)return;time+=dt;cooldown=Math.max(0,cooldown-dt);shake=Math.max(0,shake-dt);
  const x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+stick.x;
  const z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+stick.y;
  const run=keys.has('ShiftLeft')||keys.has('ShiftRight')||touchRun,speed=run?actor.groundSpeeds.Running*1.3:actor.groundSpeeds.Walking;
  desired.set(x,0,z);if(desired.lengthSq()>1)desired.normalize();desired.applyAxisAngle(up,inputYaw).multiplyScalar(speed*(actor.locked&&jump<=0?0:1));velocity.lerp(desired,1-Math.exp(-dt*13));
  if(velocity.length()>.025){const angle=Math.atan2(velocity.x,velocity.z),delta=Math.atan2(Math.sin(angle-actor.root.rotation.y),Math.cos(angle-actor.root.rotation.y));actor.root.rotation.y+=delta*(1-Math.exp(-dt*17));}
  const p=actor.root.position,oldX=p.x,oldZ=p.z,nx=p.x+velocity.x*dt,nz=p.z+velocity.z*dt;if(!blocked(nx,p.z))p.x=nx;if(!blocked(p.x,nz))p.z=nz;const travel=Math.hypot(p.x-oldX,p.z-oldZ),actual=travel/dt;
  if(jump>0||vertical>0){vertical-=15.5*dt;jump+=vertical*dt;if(jump<=0){jump=vertical=0;fx.puff(new THREE.Vector3(p.x,env.height(p.x,p.z)+.08,p.z),{count:13,size:.13,speed:1.8});event('land');}}
  p.y=env.height(p.x,p.z)+Math.max(0,jump);actor.tick(dt,actual,contact);dust+=travel;if(dust>.7&&jump===0){dust=0;fx.puff(p.clone().add(new THREE.Vector3(0,.07,0)),{count:3,color:'#c5c8a7',speed:.4,life:.5,size:.09,up:.2,gravity:.6});}
  friend.tick(dt,0);if(Math.floor(time/7)!==Math.floor((time-dt)/7))friend.action('Wave',2.2);
  for(const t of targets){t.recoil=Math.max(0,t.recoil-dt);for(const m of t.root.userData.paint)m.material.color.copy(m.color).lerp(flashColor,Math.max(0,t.recoil-.27)*3);t.root.rotation.z=Math.sin((.42-t.recoil)*20)*t.recoil*.32;t.root.position.y=env.height(t.root.position.x,t.root.position.z);if(t.recover>0){t.recover-=dt;t.root.scale.setScalar(Math.max(.03,Math.min(1,t.recover>1.7?(t.recover-1.7)/.7:(.5-t.recover)*2)));if(t.recover<=0){t.hp=3;t.root.scale.setScalar(1);fx.ring(t.root.position.clone().add(new THREE.Vector3(0,.1,0)),{radius:1.3,color:'#b9eac5'});}}}
  towerTime+=dt;tower.children[0].position.z=tower.userData.baseZ-.18*Math.exp(-((towerTime%4)/.17));if(towerTime>=4&&!shot){towerTime=0;const from=tower.position.clone().add(new THREE.Vector3(.8,2,0)),to=targets[2].root.position.clone().add(new THREE.Vector3(0,1.2,0));shot={from,to,t:0};fx.hit(from);event('cannon-fire');}
  if(shot){shot.t+=dt;const t=Math.min(1,shot.t/.48);projectile.visible=true;projectile.position.lerpVectors(shot.from,shot.to,t);projectile.position.y+=Math.sin(t*Math.PI)*.65;if(t===1){fx.hit(shot.to);targets[2].recoil=.42;projectile.visible=false;shot=null;event('cannon-impact');}}
  fx.tick(dt);env.animate(time);follow.lerp(v.copy(p).add(new THREE.Vector3(0,1.5,0)),1-Math.exp(-dt*8));
  uiTime+=dt;if(uiTime>.15){uiTime=0;$('#action-status').textContent=jump>.05?'Jump':actor.current==='Wave'?'Pulse':actor.current==='Punch'?'Strike':actor.current;let nearest=targets.reduce((a,b)=>a.root.position.distanceTo(p)<b.root.position.distanceTo(p)?a:b);$('#target-status').textContent=nearest.name+' · '+nearest.root.position.distanceTo(p).toFixed(1)+' m';$('#touch-pulse').textContent=cooldown>0?cooldown.toFixed(1)+' s':'Pulse';}
}
function draw(){if(!ready||lost)return;const r=$('#stage').getBoundingClientRect(),w=Math.round(r.width),h=Math.round(r.height),dpr=renderer.getPixelRatio();if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr))renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();const d=distance*(camera.aspect<.8?1.22:1);camera.position.set(follow.x+Math.sin(yaw)*Math.cos(pitch)*d,follow.y+Math.sin(pitch)*d,follow.z+Math.cos(yaw)*Math.cos(pitch)*d);camera.position.y=Math.max(camera.position.y,env.height(camera.position.x,camera.position.z)+1);camera.lookAt(follow);if(shake&&!reduced.matches)camera.rotation.z=Math.sin(time*80)*shake*.035;paint.setVariant(state.style,state,w,h,scene);scene.fog.density=VERSIONS[state.style].fog;sun.shadow.radius=VERSIONS[state.style].shadowRadius;renderer.render(scene,camera);}
function frame(now){requestAnimationFrame(frame);const elapsed=Math.max(0,now-last),dt=Math.min(elapsed/1000,.05);last=now;if(!ready||lost||document.hidden)return;if(!state.paused){timings.push(elapsed);if(timings.length>900)timings.shift();step(dt);}draw();}

document.querySelectorAll('[data-style]').forEach(b=>b.addEventListener('click',()=>style(b.dataset.style)));$('#pause').onclick=()=>pause(!state.paused);$('#reset').onclick=reset;$('#retry').onclick=()=>location.reload();$('#capture').onclick=()=>{if(!ready||lost)return;draw();const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='worldheart-playground-'+state.style+'.png';a.click();};
window.addEventListener('keydown',e=>{if(!ready||e.target.closest('input,select')||(e.code==='Space'&&e.target.closest('button,a')))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','ShiftRight','KeyJ','KeyE','KeyP'].includes(e.code)){e.preventDefault();if(!keys.size)inputYaw=yaw;keys.add(e.code);if(!e.repeat){if(e.code==='KeyJ')attack('strike');if(e.code==='KeyE')attack('pulse');if(e.code==='Space')leap();if(e.code==='KeyP')pause(!state.paused);}}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{clearInput();last=performance.now();});
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});if(e.button===2||e.pointerType==='touch'){orbit={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);}else if(e.button===0)attack('strike');});canvas.addEventListener('pointermove',e=>{if(orbit?.id!==e.pointerId)return;yaw-=(e.clientX-orbit.x)*.006;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-orbit.y)*.004,.07,1.1);orbit.x=e.clientX;orbit.y=e.clientY;});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,()=>orbit=null);canvas.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance*Math.exp(e.deltaY*.001),4,19);},{passive:false});
document.querySelectorAll('[data-station]').forEach(b=>b.addEventListener('click',()=>{if(!ready)return;reset();const spots={meadow:[0,10,0],brook:[9,7,.3],cannon:[-7,17,-.25]},s=spots[b.dataset.station];actor.root.position.set(s[0],env.height(s[0],s[1]),s[1]);yaw=inputYaw=s[2];follow.copy(actor.root.position).add(new THREE.Vector3(0,1.5,0));canvas.focus({preventScroll:true});}));
const pad=$('#stick');function padMove(e){if(stickPointer!==e.pointerId)return;const r=pad.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.max(38,Math.hypot(dx,dy));stick.x=dx/len;stick.y=dy/len;$('#thumb').style.transform=`translate(${stick.x*34}px,${stick.y*34}px)`;}pad.addEventListener('pointerdown',e=>{e.preventDefault();stickPointer=e.pointerId;inputYaw=yaw;pad.setPointerCapture(e.pointerId);padMove(e);});pad.addEventListener('pointermove',padMove);for(const name of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(name,()=>{stickPointer=null;stick.x=stick.y=0;$('#thumb').style.transform='';});$('#touch-run').onclick=()=>{touchRun=!touchRun;$('#touch-run').setAttribute('aria-pressed',String(touchRun));};$('#touch-strike').onclick=()=>attack('strike');$('#touch-pulse').onclick=()=>attack('pulse');$('#touch-jump').onclick=leap;

async function boot(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.VSMShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
    paint=await createCandidateMaterials();env=createPaintedEnvironment(paint);scene.add(env.root);fx=createEffects(scene);$('#load-status').textContent='Binding authored clips to painted materials…';actor=await createActor(paint,{color:'#c1b388'});scene.add(actor.root);friend=await createActor(paint,{color:'#8facaa'});friend.root.position.set(-1,env.height(-1,0),0);scene.add(friend.root);await specimens();
    window.PLAYGROUND={state,actor,friend,targets,events,step,render:draw,get ready(){return ready;},get time(){return time;},get camera(){return {yaw,pitch,distance};},get timings(){return timings.slice();},get metrics(){return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,effects:fx.active,emitted:fx.emitted};},get movement(){return {velocity:velocity.toArray(),jump,cooldown};},get reducedMotion(){return reduced.matches;},get contextLost(){return lost;}};
    ready=true;reset();style(state.style);$('#action-status').textContent='Idle';$('#loading').hidden=true;canvas.focus({preventScroll:true});draw();last=performance.now();requestAnimationFrame(frame);
    canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;clearInput();$('#loading').hidden=false;$('#load-status').textContent='Graphics interrupted. Waiting to restore…';$('#capture').disabled=true;});canvas.addEventListener('webglcontextrestored',()=>{lost=false;last=performance.now();$('#loading').hidden=true;$('#capture').disabled=false;});
  }catch(e){window.PLAYGROUND_ERROR=String(e);$('#loading h2').textContent='The meadow could not finish loading';$('#load-status').textContent=e.message;$('#retry').hidden=false;$('#capture').disabled=true;console.error(e);}}
boot();
