import * as THREE from '../lib/three.module.min.js';
import {ModelPreview} from './asset-model-viewer.js';
const $=s=>document.querySelector(s),base='../../lib/99-art/vey-pilot-v1/';
const [manifest,charts,paint]=await Promise.all(['manifest.json','motion-chart.json','paint-receipt.json'].map(n=>fetch(base+n).then(r=>r.json())));
$('#palette').innerHTML=manifest.palette.map(p=>`<div class="swatch"><i style="background:${p.hex}"></i><span>${p.name}<code>${p.hex}</code></span></div>`).join('');
$('#coverage').textContent=`Reference cameras currently cover ${Math.round(paint.referenceCoverage*100)}% of sampled surface texels. Orange areas in the coverage map use a material palette fill and still need manual inspection. The pilot has ${paint.triangles.toLocaleString()} triangles and a ${paint.textureSize}px embedded texture. Roblox import acceptance is a separate step.`;
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(manifest.prompt);$('#copy-status').textContent='Prompt copied.';}catch{$('#copy-status').textContent='Use the Text prompt download to copy it.';}};
const preview=new ModelPreview($('#viewer'));preview.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));
preview.scene.children.filter(o=>o.isLight).forEach(o=>o.intensity*=.55);
const grid=new THREE.GridHelper(12,40,0x9fa99f,0xc4ccc1);grid.position.y=.002;preview.scene.add(grid);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.MeshBasicMaterial({color:0xd9ded8}));ground.rotation.x=-Math.PI/2;ground.position.y=-.005;preview.scene.add(ground);
let current,travel=0,groundSpeed=0,clipName='Walk',chartCursor;
const rigControl=document.createElement('label');rigControl.innerHTML='<input id="show-rig" type="checkbox"> Rig & 3D motion chart';$('.controls').append(rigControl);let skeleton,trails;
function clearRigChart(){for(const item of [skeleton,trails])if(item){preview.scene.remove(item);item.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}skeleton=trails=null;}
function updateRigChart(){clearRigChart();skeleton=new THREE.SkeletonHelper(preview.root);skeleton.material.depthTest=false;skeleton.material.transparent=true;skeleton.material.opacity=.8;skeleton.renderOrder=5;preview.scene.add(skeleton);trails=new THREE.Group();const c=charts[clipName];if(c)for(let i=0;i<2;i++){const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(c.feet.map(p=>new THREE.Vector3(p[i][0],p[i][2],-p[i][1]))),new THREE.LineBasicMaterial({color:i?0x895ca6:0x297b69,depthTest:false}));line.renderOrder=5;trails.add(line);}preview.scene.add(trails);skeleton.visible=trails.visible=$('#show-rig').checked;}
$('#show-rig').onchange=()=>{if(skeleton)skeleton.visible=trails.visible=$('#show-rig').checked;};
function chart(){const c=charts[clipName];if(!c){$('#chart').innerHTML='';return;}const lines=[0,1].map((leg)=>{const d=c.feet.map((f,i)=>`${i?'L':'M'}${20+i/(c.feet.length-1)*660},${140-Math.max(0,f[leg][2]-.06)*420}`).join(' ');return `<path d="${d}" fill="none" stroke="${leg?'#895ca6':'#297b69'}" stroke-width="3"/>`;});$('#chart').innerHTML=`<path d="M20 140H680" stroke="#a1ada4"/><text x="20" y="19" font-size="12" fill="#355e53">LEFT</text><text x="85" y="19" font-size="12" fill="#744694">RIGHT</text><text x="535" y="19" font-size="12" fill="#355e53">${c.seconds.toFixed(2)} s / cycle</text>${lines.join('')}<path id="cursor" d="M20 30V145" stroke="#303d3a" stroke-width="1"/>`;chartCursor=$('#cursor');}
function selectClip(name,fade=true){clipName=name;$('#clip').value=name;const clip=preview.clips?.find(c=>c.name.startsWith(name));if(!clip)return;if(!fade){preview.mixer.stopAllAction();current=null;}const next=preview.mixer.clipAction(clip);next.reset().setEffectiveWeight(1).play();if(current&&current!==next)current.crossFadeTo(next,.22,false);current=next;preview.playing=true;$('#play').textContent='Pause';chart();updateRigChart();}
async function load(){window.VEY_PILOT.ready=false;clearRigChart();preview.pauseRendering(true);$('#status').textContent='Loading model...';const stage=$('#stage').value;const file=stage==='motion'?base+'vey-motion.glb':stage==='paint'?base+'paint-review.glb':'../../lib/99-art/identity-v2/vey-hunyuan-painted.glb';await preview.load(file);current=null;$('#clip').disabled=stage!=='motion';$('#show-rig').disabled=stage!=='motion';if(stage==='motion'){preview.mixer.stopAllAction();selectClip($('#clip').value);}preview.pauseRendering(false);preview.yaw=.35;preview.pitch=.1;$('#status').textContent=stage==='motion'?'CMU motion capture / hand-placed 22-bone rig / drag to orbit / walk ↔ run blends over 0.22 s':'Drag to orbit. Compare the face, mantle, cuffs and rear surfaces.';window.VEY_PILOT.ready=true;}
const draw=preview.draw.bind(preview);let last=performance.now();preview.draw=function(){const now=performance.now(),dt=Math.min((now-last)/1000,.08);last=now;if(preview.playing&&!preview.paused&&$('#floor').checked&&$('#stage').value==='motion'){const speed=charts[clipName]?.speed||0;groundSpeed+=(speed-groundSpeed)*(1-Math.exp(-dt/.12));travel=(travel+groundSpeed*dt*preview.speed)%.3;grid.position.z=-travel;}draw();if(chartCursor&&current){const x=20+(current.time/current.getClip().duration%1)*660;chartCursor.setAttribute('d',`M${x} 30V145`);}};
$('#stage').onchange=load;$('#clip').onchange=e=>selectClip(e.target.value);$('#play').onclick=()=>$('#play').textContent=preview.toggle()?'Pause':'Play';$('#speed').oninput=e=>preview.speed=+e.target.value;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{preview.yaw={front:0,side:Math.PI/2,back:Math.PI,three:.5}[b.dataset.view];preview.pitch=.06;});
window.VEY_PILOT={ready:false,preview,selectClip,step(time){preview.mixer?.setTime(time);preview.draw();}};
try{await load();}catch(e){$('#status').textContent=e.message;window.VEY_PILOT.error=e.message;}
