import * as THREE from 'three';
import {GLTFLoader} from '../lib/addons/loaders/GLTFLoader.js';
import {createSurfaceMaterials,GRAPHICS_DEFAULTS} from './arena-materials.js';
import {createWorlds} from './arena-world.js';
import {kit} from './arena-kit.js';
const $=s=>document.querySelector(s),canvas=$('#field'),keys=new Set();
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,stencil:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(48,1,.08,160),ambient=new THREE.HemisphereLight('#e2ebdc','#515f51',1.8),sun=new THREE.DirectionalLight('#ffe6b8',2.2);sun.position.set(-13,24,13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:25,bottom:-25,near:1,far:70});sun.shadow.normalBias=.018;sun.shadow.bias=-.0001;scene.add(ambient,sun);
let worlds,world,paint,hero,patrols=[],towers=[],active=false,ready=false,paused=false,yaw=.3,pitch=.32,distance=5.4,flight=false,last=performance.now(),time=0,drag;
const pos=new THREE.Vector3(0,0,8),velocity=new THREE.Vector3(),free=new THREE.Vector3(),target=new THREE.Vector3(),camTarget=new THREE.Vector3(),events=[],frames=[];
const speeds={Walk:1.389573589,Run:3.461958244};
function event(type,data={}){events.push({type,time,...data});if(events.length>200)events.shift();}
function cloneRig(source){const copy=source.clone(true),a=[],b=[],map=new Map();source.traverse(o=>a.push(o));copy.traverse(o=>b.push(o));a.forEach((o,i)=>map.set(o,b[i]));a.forEach(o=>{if(o.isSkinnedMesh){const c=map.get(o);c.skeleton=o.skeleton.clone();c.skeleton.bones=o.skeleton.bones.map(x=>map.get(x));c.bind(c.skeleton,o.bindMatrix);}});return copy;}
function actor(root,clips){
 const wrapper=new THREE.Group();wrapper.add(root);scene.add(wrapper);const mixer=new THREE.AnimationMixer(root),actions={};
 for(const clip of clips){const name=clip.name.split(' ')[0];actions[name]=mixer.clipAction(clip).play();actions[name].setEffectiveWeight(name==='Idle'?1:0);}
 const meshes=[];root.traverse(o=>{if(o.isMesh)meshes.push(o);});
 for(const mesh of meshes){mesh.castShadow=mesh.receiveShadow=true;mesh.frustumCulled=false;mesh.material=mesh.material.clone();mesh.material.emissiveMap=mesh.material.map;mesh.material.emissive=new THREE.Color('white');mesh.material.emissiveIntensity=.22;if(mesh.material.map){mesh.material.map.colorSpace=THREE.SRGBColorSpace;mesh.material.map.anisotropy=renderer.capabilities.getMaxAnisotropy();}mesh.material.stencilWrite=true;mesh.material.stencilRef=1;mesh.material.stencilFunc=THREE.AlwaysStencilFunc;mesh.material.stencilZPass=THREE.ReplaceStencilOp;
  const outline=mesh.clone(false),m=new THREE.MeshBasicMaterial({color:'#151c22',side:THREE.BackSide,stencilWrite:true,stencilRef:1,stencilFunc:THREE.NotEqualStencilFunc,stencilZPass:THREE.KeepStencilOp});m.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed+=normalize(normal)*0.0038;');};outline.material=m;outline.renderOrder=1;outline.castShadow=false;outline.receiveShadow=false;if(mesh.isSkinnedMesh){outline.skeleton=mesh.skeleton;outline.bindMatrix.copy(mesh.bindMatrix);outline.bindMatrixInverse.copy(mesh.bindMatrixInverse);}mesh.parent.add(outline);
 }
 return {root:wrapper,mixer,actions,speed:0,update(dt,speed){this.speed=speed;const moving=THREE.MathUtils.smoothstep(speed,.015,.35),running=THREE.MathUtils.smoothstep(speed,1.6,2.8),weights={Idle:1-moving,Walk:moving*(1-running),Run:moving*running};for(const [name,a]of Object.entries(actions)){a.setEffectiveWeight(THREE.MathUtils.damp(a.getEffectiveWeight(),weights[name]||0,14,dt));a.timeScale=name==='Idle'?1:Math.max(.12,speed/speeds[name]);}mixer.update(dt);}};
}
function ground(x,z){let h=world.height(x,z);if(world.id!=='meadow'){const ruin=world.id==='ruins',n=ruin?10:7;for(let i=0;i<n;i++){const cx=ruin?Math.sin(i)*.25:Math.sin(i*.7)*.4,cz=ruin?-16+i*3.2:-10+i*3,rot=ruin?Math.sin(i)*.12:i*.04,dx=x-cx,dz=z-cz,rx=dx*Math.cos(rot)-dz*Math.sin(rot),rz=dx*Math.sin(rot)+dz*Math.cos(rot);if(Math.abs(rx)<1.02&&Math.abs(rz)<1.3)h=Math.max(h,world.height(cx,cz)+.14);}}return h;}
function reset(){pos.set(0,ground(0,8),8);velocity.set(0,0,0);hero.root.position.copy(pos);hero.root.rotation.y=Math.PI;yaw=.3;pitch=.32;distance=5.4;flight=false;$('#fly').textContent='F · Free camera';keys.clear();camTarget.copy(pos).add(new THREE.Vector3(0,1.15,0));event('reset');}
function selectWorld(id){world=worlds.find(w=>w.id===id)||worlds[0];worlds.forEach(w=>w.root.visible=w===world);scene.background=new THREE.Color(world.sky);scene.fog=new THREE.FogExp2(world.sky,.012);sun.color.set(world.sun);ambient.color.set(world.ambient);document.querySelectorAll('[data-world]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.world===world.id)));towers.forEach((t,i)=>{const x=i?7:-7,z=i?7:9;t.root.position.set(x,world.height(x,z),z);});reset();event('world',{id:world.id});}
function toggleFlight(){flight=!flight;keys.clear();velocity.set(0,0,0);if(flight)free.copy(camera.position);$('#fly').textContent=flight?'F · Return to Vey':'F · Free camera';event('flight',{enabled:flight});}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}addEventListener('resize',resize);resize();
function clear(){keys.clear();drag=null;}addEventListener('blur',()=>{clear();paused=true;});addEventListener('focus',()=>{paused=false;last=performance.now();});document.addEventListener('visibilitychange',()=>{paused=document.hidden;clear();last=performance.now();});
addEventListener('keydown',e=>{if(e.target!==canvas&&/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ControlLeft','ShiftLeft'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='KeyF'&&!e.repeat&&active)toggleFlight();});addEventListener('keyup',e=>keys.delete(e.code));
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);canvas.focus();};canvas.onpointermove=e=>{if(!drag)return;yaw-=(e.clientX-drag[0])*.006;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-drag[1])*.004,-.2,1.05);drag=[e.clientX,e.clientY];};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*.006,2.2,12);},{passive:false});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();keys.add(b.dataset.key);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);});
$('#enter').onclick=()=>{active=true;$('#welcome').hidden=true;$('#hud').hidden=false;canvas.focus();event('enter');};$('#fly').onclick=toggleFlight;$('#reset').onclick=reset;$('#help').onclick=()=>{clear();paused=true;$('#controls').showModal();};function resume(){clear();paused=false;last=performance.now();canvas.focus();}$('#close').onclick=()=>$('#controls').close();$('#controls').addEventListener('close',resume);document.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>selectWorld(b.dataset.world));
function update(dt){time+=dt;const f=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),r=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),run=keys.has('ShiftLeft'),input=new THREE.Vector3(r*Math.cos(yaw)-f*Math.sin(yaw),0,-r*Math.sin(yaw)-f*Math.cos(yaw));if(input.lengthSq()>1)input.normalize();
 if(active&&flight){free.addScaledVector(input,dt*(run?12:5));free.y+=dt*5*((keys.has('Space')?1:0)-(keys.has('ControlLeft')?1:0));free.y=Math.max(world.height(free.x,free.z)+.4,free.y);hero.update(dt,0);camera.position.copy(free);camera.lookAt(free.x-Math.sin(yaw)*Math.cos(pitch),free.y-Math.sin(pitch),free.z-Math.cos(yaw)*Math.cos(pitch));}
 else{
  const speed=active?(run?speeds.Run:speeds.Walk):0;velocity.x=THREE.MathUtils.damp(velocity.x,input.x*speed,10,dt);velocity.z=THREE.MathUtils.damp(velocity.z,input.z*speed,10,dt);const before=pos.clone(),nx=pos.x+velocity.x*dt,nz=pos.z+velocity.z*dt;if(!world.blocked(nx,pos.z,.32))pos.x=nx;else velocity.x=0;if(!world.blocked(pos.x,nz,.32))pos.z=nz;else velocity.z=0;pos.y=ground(pos.x,pos.z);const actual=Math.hypot(pos.x-before.x,pos.z-before.z)/Math.max(dt,.0001);hero.root.position.copy(pos);if(actual>.03){const angle=Math.atan2(velocity.x,velocity.z),delta=Math.atan2(Math.sin(angle-hero.root.rotation.y),Math.cos(angle-hero.root.rotation.y));hero.root.rotation.y+=delta*(1-Math.exp(-12*dt));}hero.update(dt,actual);
  target.copy(pos).add(new THREE.Vector3(0,1.18,0));camTarget.lerp(target,1-Math.exp(-12*dt));const wish=camTarget.clone().add(new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance));let t=1;for(let j=1;j<=20;j++){const q=camTarget.clone().lerp(wish,j/20);if(q.y<world.height(q.x,q.z)+.25||world.obstacles.some(([x,z,rad])=>Math.hypot(q.x-x,q.z-z)<rad+.15&&q.y<world.height(x,z)+rad*2.5)){t=Math.max(.12,(j-1)/20);break;}}camera.position.copy(camTarget).lerp(wish,t);camera.lookAt(camTarget);$('#motion-status').textContent=actual<.08?'Standing':actual>2?'Running':'Walking';
 }
 for(const [i,a]of patrols.entries()){const z=3-i*7,x=-4+i*8+Math.sin(time*.24+i)*2.3,spd=Math.abs(Math.cos(time*.24+i)*.24*2.3);a.root.position.set(x,ground(x,z),z);a.root.rotation.y=Math.cos(time*.24+i)>0?Math.PI/2:-Math.PI/2;a.update(dt,spd);}
 towers.forEach((t,i)=>t.head.rotation.y=Math.sin(time*.25+i)*.45);world.animate?.(time);paint.setVariant('v5',{ink:true,paint:true,light:'golden'},innerWidth,innerHeight,scene);paint.tune(GRAPHICS_DEFAULTS);
}
function frame(now){const actualMs=now-last,dt=Math.min(actualMs/1000,.05);last=now;if(ready&&!paused){update(dt);renderer.render(scene,camera);if(active){frames.push(actualMs);if(frames.length>600)frames.shift();}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
try{paint=await createSurfaceMaterials();worlds=createWorlds(paint);worlds.forEach(w=>scene.add(w.root));const k=kit(paint);towers=[k.tower('cannon'),k.tower('beacon')];towers.forEach(t=>scene.add(t.root));const gltf=await new GLTFLoader().loadAsync('lib/99-art/vey-articulation-v1/vey-motion.glb');const clones=[cloneRig(gltf.scene),cloneRig(gltf.scene)];hero=actor(gltf.scene,gltf.animations);patrols=clones.map(s=>actor(s,gltf.animations));selectWorld('meadow');ready=true;$('#enter').disabled=false;$('#enter').textContent='Enter the frontier';$('#load-status').textContent='Ready · accepted model, original 4K paint';window.VEY_FIELD={get ready(){return ready;},get state(){return {active,flight,world:world.id,position:pos.toArray(),speed:hero.speed,clips:Object.keys(hero.actions),calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,frames:frames.slice(),events:events.slice()};},hero,patrols,worlds,selectWorld,reset};}catch(e){$('#load-status').textContent='Could not load: '+e.message;console.error(e);}
