import {MotionGuide} from './motion-guide.js';
import {ModelPreview} from '/js/asset-model-viewer.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let referenceView='hero';
let config,project,view='art',modelURL='',toastTimer,saveTimer,dirty=false;const preview=new ModelPreview($('#model-canvas'),{contourMode:'silhouette'});
window.STUDIO_REVIEW={preview};
const motionGuide=new MotionGuide($('#preview').parentNode,{api,safe,refresh:p=>{project=p;render();}});
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{preview.yaw=+b.dataset.camera;preview.pitch=.05;preview.draw();});
async function api(path,method='GET',body){const r=await fetch('/api/'+path,{method,headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.detail||'Request failed');return data;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
async function safe(fn){try{return await fn();}catch(e){toast(e.message);}}
function url(name){return '/files/projects/'+project.id+'/'+encodeURIComponent(name);}
async function refreshList(){const rows=await api('projects');$('#projects').innerHTML=rows.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(project)$('#projects').value=project.id;return rows;}
async function load(id){await flush();project=await api('projects/'+id);referenceView='hero';localStorage.setItem('asset-studio-project',id);$('#name').value=project.name;$('#description').value=project.description;$('#style').value=project.style;view=project.polished?'polished':project.animation?'animation':project.paint?'paint':project.mesh?'mesh':'art';if(location.hash==='#motion-video-guide')view='animation';modelURL='';render();if(location.hash==='#motion-video-guide'){motionGuide.panel.open=true;motionGuide.panel.scrollIntoView();}}
async function flush(){clearTimeout(saveTimer);if(!dirty||!project)return;const p=await api('projects/'+project.id,'PUT',{name:$('#name').value,description:$('#description').value,style:$('#style').value});project=p;dirty=false;await refreshList();render();}
function changed(){dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>safe(flush),650);}
for(const id of ['name','description','style'])$('#'+id).addEventListener('input',changed);
function button(text,action,primary=false){return `<button data-action="${action}" class="${primary?'primary':''}">${text}</button>`;}
function render(){if(!project)return;motionGuide.update(project,view);const busy=['queued','running'].includes(project.status),pack=project.referencePack,views={...pack?.outputs,...(project.rigReference?{tpose:project.rigReference}:{})},name=view==='art'&&referenceView!=='hero'?(views[referenceView]?.file||project.art):(project[view]||(view==='animation'?(project.paint||project.mesh):null));$('#asset-title').textContent=project.name;$('#cancel').hidden=!busy;$('#busy').hidden=!busy;$('#busy-stage').textContent=project.stage+' / '+project.message;$('#status-title').textContent=project.status==='error'?'Job needs attention':project.status==='approved'?(project.reviews?.[view]?.reviewer==='agent'?'Candidate / owner review pending':'Approved'):busy?'Local job in progress':view==='art'?'Review the concept':view==='animation'?'Review the complete motion':view==='polished'?(project.reviews?.animation?.ownerApproved?'Production package':'Review candidate package'):'Inspect the model';$('#status-message').textContent=project.status==='error'?project.message.trim().split('\n').at(-1).slice(0,360):project.message;$('#shape-conditioning').textContent=project.shapeConditioning?('Shape inputs: '+Object.keys(project.shapeConditioning.views).join(', ')+'. '+project.shapeConditioning.note+(project.shapeBudget?' '+project.shapeBudget.note:'')):'';$('#generate').disabled=busy;for(const id of ['name','description','style','upload'])$('#'+id).disabled=busy;
 $('#reference-pack').hidden=view!=='art'||!Object.keys(views).length;$('#reference-view').innerHTML='<option value="hero">Main reference</option>'+Object.keys(views).filter(k=>!['palette','prompt','cameras'].includes(k)).map(k=>`<option value="${esc(k)}">${esc(k==='sheet'?'Six views + palette':k==='motion'?'Walk + strike guide':k==='tpose'?'T-pose / rigging guide':k)}</option>`).join('');$('#reference-view').value=referenceView;$('#reference-status').textContent=pack?(pack.provider||'Local Krea')+' / '+(pack.complete?'Review identity across all views':'Incomplete: resume the saved pack')+(pack.calibrated?' / cameras recorded':' / uncalibrated design guides'):'';$('#reference-prompt').hidden=!pack?.outputs?.prompt;$('#reference-prompt').href=pack?.outputs?.prompt?url(pack.outputs.prompt.file):'';
 $('#use-reference').hidden=busy||!project.references.length;$('#references').innerHTML=project.references.map((n,i)=>`<figure><img src="${url(n)}" alt="Reference ${i+1}"><button data-remove="${i}" aria-label="Remove reference ${i+1}" ${busy?'disabled':''}>Ã-</button></figure>`).join('');
 document.querySelectorAll('[data-view]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.view===view);b.disabled=b.dataset.view!=='art'&&!project[b.dataset.view]&&!(b.dataset.view==='animation'&&(project.paint||project.mesh));});
 $('#art-preview').hidden=view!=='art'||!name;$('#model-canvas').hidden=view==='art'||!name;$('#viewer-controls').hidden=view==='art'||!name;$('#empty').hidden=!!name;
 if(view==='art'&&name){const target=url(name);if($('#art-preview').getAttribute('src')!==target)$('#art-preview').src=target;preview.pauseRendering(true);}
 else if(name){preview.pauseRendering(false);if(modelURL!==name){modelURL=name;preview.load(url(name)).then(clips=>{$('#clips').innerHTML=clips.length?clips.map(c=>`<option>${esc(c)}</option>`).join(''):'<option>No animation</option>';$('#clips').disabled=!clips.length;$('#play').disabled=!clips.length;$('#scrub').disabled=!clips.length;preview.surfaceMode($('#surface-mode').value);preview.focus($('#focus-part').value);}).catch(e=>toast(e.message));}}
 if(!name||busy)preview.pauseRendering(true);let actions='';if(!busy){if(view==='art'&&project.art){actions+=button('Make T-pose guide','reference-tpose')+button(project.referenceMode==='model'?'Switch to generated guides':'Use exact model views','reference-mode');if(!project.referencePackExpected||pack?.complete)actions+=button(project.approvals.art&&(!pack||project.approvals.referencePack)?'2D approved':project.referenceMode==='model'&&!pack?'Approve hero':'Approve hero + pack','approve-art');if(project.referenceMode!=='model')actions+=button('Test front view','reference-front')+button(project.referencePack?.complete?'Resume missing references':'Build remaining references','references');if(['front','left','right','back','top','bottom','motion'].includes(referenceView))actions+=button('Retry this view','reference-'+referenceView)+(referenceView!=='motion'?button('Isolate one figure','isolate-figure'):'');actions+=button('Use this concept as next reference','use-concept-reference');if(project.mesh)actions+=button('Render exact model references','model-references');if(project.approvals.art&&(!pack||project.approvals.referencePack))actions+=button('Make model','mesh',true)+button('Run through motion','production');}else if(view==='mesh'&&project.mesh)actions=button('Paint model','paint',true)+button('Rig and animate','animation');else if(view==='paint')actions=button('Rig and animate','animation',true);else if(view==='animation'&&!project.animation)actions='<p class="hint">Fit a local MIA skeleton, preserve this paint, then add a captured walk. Review the result before polishing.</p>'+button('Rig and animate','animation',true);else if(view==='animation'&&project.animation){actions=button('Render exact model references','model-references')+button(project.approvals.animation?'Animation approved':'Approve animation','approve-animation');if(project.approvals.animation)actions+=button('Polish & package','polish',true);}else if(view==='polished'&&project.polished)actions=`<a class="download" href="/api/projects/${project.id}/export">Download asset package â†“</a>`;}if(!busy&&['paint','animation'].includes(view))actions+=button(views.tpose?'View T-pose guide':'Make T-pose guide',views.tpose?'show-tpose':'reference-tpose');if(!busy&&project.refinementProfile&&['paint','animation'].includes(view))actions+=button('Replay complete Vey refinement','refined-production')+button('Refine hands & foot roll','articulate');if(!busy&&project.paintProfile&&project.rigProfile)actions+=button('Save fitted recipe','save-recipe');if(!busy&&project.productionRecipe)actions+=button('Replay fitted production','replay-fitted');$('#actions').innerHTML=actions;
 $('#paint-fit').hidden=!project.paint;$('#save-paint-fit').disabled=$('#paint-fit-file').disabled=busy;$('#rig-fit').hidden=!project.mesh;$('#open-rig-fit').href='/fit.html?project='+project.id;$('#open-motion').href='/motion.html?project='+project.id;$('#rig-fit-file').disabled=$('#clear-rig-fit').disabled=busy;$('#clear-rig-fit').hidden=!project.rigProfile;$('#rig-fit-status').textContent=project.rigProfile?project.rigProfile.name+' / bound to this model':'Rig and animate uses local MIA rigging and a captured walk. Fit joints manually here when anatomical correction is needed.';$('#rig-fit-download').hidden=!project.rigProfile;$('#rig-fit-download').href=project.rigProfile?url(project.rigProfile.file):'';
 const currentFile=project[view],qr=project.quality?.[view]?.file===currentFile?project.quality[view]:null;$('#quality-panel').hidden=!currentFile||view==='art';$('#validate-model').disabled=busy;$('#quality-report').innerHTML=qr?`<p><strong>${qr.status==='fail'?'Needs correction':'Technical checks complete; visual review pending'}</strong></p><ul>${qr.checks.map(c=>`<li>${c.status==='pass'?'âœ“':'Ã-'} ${esc(c.name)}</li>`).join('')}</ul><p class="hint">Checks cannot certify likeness or good animation. Compare the reference, inspect every side and watch complete clips.</p><a href="${url(qr.reportFile)}" download>Download full report</a>`:'<p>Run checks on this exact file before continuing.</p>';$('#downloads').innerHTML=['art','mesh','paint','animation','polished'].filter(k=>project[k]).map(k=>`<a href="${url(project[k])}" download>${esc(k)} / ${esc(project[k])} â†“</a>`).join('');$('#downloads').innerHTML+=(project.conceptHistory||[]).map((c,i)=>`<a href="${url(c.file)}" download>Earlier concept ${i+1} â†“</a>`).join('');if(project.failureDiagnostic)$('#downloads').innerHTML+=`<a href="${url(project.failureDiagnostic)}" download>Last failed attempt / diagnostic</a>`;const attempts=project.timings||[];$('#timings').innerHTML=attempts.length?'<h3>Step timings</h3><p class="hint">Execution time, including failures. Approval and queue waits are separate.</p><ul>'+attempts.map(t=>`<li>${esc(t.stage)} Â· ${t.seconds===undefined?(Math.max(0,(Date.now()-Date.parse(t.startedAt))/1000).toFixed(0)+' s elapsed'):t.seconds.toFixed(1)+' s'} Â· ${esc(t.status)}</li>`).join('')+`</ul><a href="${url('timings.json')}" download>Download timing receipts</a>`:'';$('#events').textContent=(project.events||[]).slice(-12).map(e=>new Date(e.time*1000).toLocaleTimeString()+' '+e.text).join('\n');}
async function run(stage){if(stage==='reference-tpose')referenceView='tpose';await flush();project=await api(`projects/${project.id}/run/${stage}?queue=true`,'POST');view=(['concept','hero','references','model-references'].includes(stage)||stage.startsWith('reference-'))?'art':stage==='polish'?'polished':stage==='production'?'mesh':['refine','articulate','refined-production','replay-fitted'].includes(stage)?'animation':stage;render();}
$('#actions').onclick=e=>safe(async()=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action==='show-tpose'){view='art';referenceView='tpose';render();}else if(action==='isolate-figure'){const data=await api(`projects/${project.id}/reference-figures/${referenceView}`);const panel=document.createElement('div');panel.className='actions';panel.textContent='Choose the figure from left to right: ';data.figures.forEach((_,index)=>{const b=document.createElement('button');b.textContent='Use figure '+(index+1);b.onclick=()=>safe(async()=>{project=await api(`projects/${project.id}/reference-figures/${referenceView}`,'POST',{index,sourceSha256:data.sourceSha256});panel.remove();render();});panel.append(b);});if(!data.figures.length)panel.textContent='No separate full-height figures detected; upload a clean single-character view.';$('#actions').append(panel);}else if(action==='save-recipe'){await flush();project=await api(`projects/${project.id}/recipe`,'POST');render();}else if(action==='reference-mode'){await flush();project=await api(`projects/${project.id}/reference-mode`,'POST',{mode:project.referenceMode==='model'?'generated':'model'});render();}else if(action==='use-concept-reference'){await flush();project=await api(`projects/${project.id}/use-concept-reference`,'POST');render();}else if(action.startsWith('approve-')){await flush();project=await api(`projects/${project.id}/approve/${action.slice(8)}`,'POST');render();}else await run(action);});
$('#validate-model').onclick=()=>safe(async()=>{project=await api(`projects/${project.id}/validate/${view}`,'POST');render();});
$('#use-reference').onclick=()=>safe(async()=>{await flush();project=await api(`projects/${project.id}/use-reference/0`,'POST');view='art';render();});
$('#reference-view').onchange=e=>{referenceView=e.target.value;render();};
$('#generate').onclick=()=>safe(()=>run('hero'));$('#cancel').onclick=()=>safe(async()=>{const r=await api(`projects/${project.id}/cancel`,'POST');toast(r.message);});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});
$('#projects').onchange=e=>safe(()=>load(e.target.value));$('#new').onclick=()=>safe(async()=>{await flush();project=await api('projects','POST',{name:'Untitled asset'});await refreshList();await load(project.id);$('#name').focus();$('#name').select();});
async function upload(file){await flush();const data=new FormData();data.append('file',file);project=await api(`projects/${project.id}/upload`,'POST',data);if(file.name.toLowerCase().endsWith('.glb'))view='mesh';render();}
$('#upload').onchange=e=>safe(async()=>{if(e.target.files[0])await upload(e.target.files[0]);e.target.value='';});
$('#paste-area').addEventListener('paste',e=>{const files=[...e.clipboardData.items].filter(i=>i.kind==='file'&&i.type.startsWith('image/')).map(i=>i.getAsFile());if(files.length){e.preventDefault();safe(async()=>{for(const f of files)await upload(f);});}});
$('#references').onclick=e=>safe(async()=>{const button=e.target.closest('[data-remove]');if(button){project=await api(`projects/${project.id}/references/${button.dataset.remove}`,'DELETE');render();}});
$('#clips').onchange=e=>preview.clip(e.target.value,{fade:.22});$('#focus-part').onchange=e=>preview.focus(e.target.value);$('#surface-mode').onchange=e=>preview.surfaceMode(e.target.value);$('#scrub').oninput=e=>{preview.seek(+e.target.value);$('#play').textContent='Play';};$('#play').onclick=()=>{$('#play').textContent=preview.toggle()?'Pause':'Play';};$('#speed').oninput=e=>preview.speed=+e.target.value;$('#contour').oninput=e=>preview.ink(+e.target.value);$('#reset-view').onclick=()=>preview.reset();
function shapeControls(){const multi=$('#meshEngine').value==='hunyuan-mv';$('#meshSteps').max=multi?30:60;if(multi)$('#meshSteps').value=Math.min(30,+$('#meshSteps').value);for(const o of $('#meshResolution').options)o.disabled=multi&&+o.value>384;if(multi&&+$('#meshResolution').value>384)$('#meshResolution').value=384;}
$('#meshEngine').onchange=shapeControls;
function fillSettings(){const s=config.settings;$('#referenceMethod').value=s.referenceMethod;$('#referenceFidelity').value=s.referenceFidelity;for(const id of ['meshEngine','paintEngine']){$('#'+id).value=s[id];$('#'+id+' option[value=trellis2]').disabled=!config.trellisReady;}$('#trellis-status').textContent=config.trellisReady?'Trellis has completed a local trial. Each result still needs visual review.':'Trellis installation and trial have not been verified yet.';$('#model').innerHTML=config.models.map(m=>`<option value="${esc(m.family+'|'+m.name)}">${esc(m.name)}</option>`).join('')||'<option>No complete model installed yet</option>';if(config.models.length)$('#model').value=s.family+'|'+s.model;$('#save-settings').disabled=!config.models.length;for(const id of ['width','height','steps','seed','meshSteps','meshResolution','textureSize','trellisSteps'])$('#'+id).value=s[id];$('#loras').innerHTML=config.loras.map(name=>{const chosen=s.loras.find(l=>l.name===name);return `<div class="lora-row"><input type="checkbox" data-lora="${esc(name)}" aria-label="Enable ${esc(name)}" ${chosen?'checked':''}><label>${esc(name)}</label><input type="number" aria-label="${esc(name)} strength" value="${chosen?.strength??.7}" min="-2" max="2" step=".05"></div>`;}).join('')||'<p class="hint">No LoRAs installed yet.</p>';$('#paths').textContent='Weights: '+config.paths.models+'\nAssets: '+config.paths.projects;shapeControls();$('#model-summary').textContent=s.model.replace('.safetensors','')+' / '+s.width+' Ã- '+s.height;}
$('#settings-open').onclick=()=>safe(async()=>{config=await api('config');fillSettings();$('#settings').showModal();});$('#rescan').onclick=()=>safe(async()=>{config=await api('config');fillSettings();toast('Installed models refreshed');});
$('#save-settings').onclick=()=>safe(async()=>{const [family,model]=$('#model').value.split('|');const s={family,model,referenceMethod:$('#referenceMethod').value,referenceFidelity:+$('#referenceFidelity').value,meshEngine:$('#meshEngine').value,paintEngine:$('#paintEngine').value,loras:[...document.querySelectorAll('[data-lora]:checked')].map(e=>({name:e.dataset.lora,strength:+e.closest('.lora-row').querySelector('input[type=number]').value}))};for(const id of ['width','height','steps','seed','meshSteps','meshResolution','textureSize','trellisSteps'])s[id]=+$('#'+id).value;config=await api('config','PUT',s);fillSettings();$('#settings').close();toast('Local settings saved');});
$('#start-engine').onclick=()=>safe(async()=>{const r=await api('runtime/start','POST');toast(r.message);});
async function health(){const s=await api('status');$('#engine-dot').className=s.comfy?'ready':'';$('#engine-label').textContent=s.comfy?'Engine ready':'Engine stopped';$('#engine-note').hidden=s.comfy;$('#hardware').textContent=s.gpu?`${s.gpu.name} / ${Math.round(s.gpu.free/1024*10)/10} GB free of ${Math.round(s.gpu.total/1024)} GB. One worker runs at a time.`:'GPU information unavailable.';}
await safe(async()=>{config=await api('config');$('#style').innerHTML=config.styles.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');fillSettings();const rows=await refreshList();if(!rows.length)project=await api('projects','POST',{name:'My first asset'});const stored=new URL(location.href).searchParams.get('project')||localStorage.getItem('asset-studio-project');await load(rows.find(p=>p.id===stored)?.id||rows[0]?.id||project.id);await refreshList();await health();});
setInterval(()=>safe(async()=>{if(!project||dirty)return;const latest=await api('projects/'+project.id);if(latest.updated!==project.updated){const wasBusy=['running','queued'].includes(project.status);project=latest;if(wasBusy&&!['running','queued'].includes(project.status)){view=(['concept','hero','references','model-references'].includes(project.stage)||project.stage.startsWith('reference-'))?'art':project.polished?'polished':project.animation?'animation':project.paint?'paint':project.mesh?'mesh':'art';await refreshList();}render();}}),1800);setInterval(()=>safe(health),15000);

$('#rig-fit-file').onchange=e=>safe(async()=>{const file=e.target.files[0];if(!file)return;project=await api(`projects/${project.id}/rig-profile`,'POST',JSON.parse(await file.text()));e.target.value='';render();});
$('#clear-rig-fit').onclick=()=>safe(async()=>{project=await api(`projects/${project.id}/rig-profile`,'DELETE');render();});

const materialNames=['Skin / body','Armor / cloth','Trim','Energy','Eyes'];
const initialPalette=['#dfdbcf','#563152','#96744c','#4dada6','#af2e4a'];
$('#paint-colors').innerHTML=materialNames.map((n,i)=>`<label>${n}<input type="color" data-material="${i}" value="${initialPalette[i]}"></label>`).join('');
$('#save-paint-fit').onclick=async()=>{try{if(!project.paint)throw Error('Paint the model first');const bytes=await fetch(url(project.paint)).then(r=>r.arrayBuffer()),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');let fit=project.paintProfile?await fetch(url(project.paintProfile.file)).then(r=>r.json()):{};if(fit.sourceSha256&&fit.sourceSha256!==hash&&!project.paintHistory?.includes(project.paintProfile?.source))fit={};fit={...fit,name:'Reviewed material palette',sourceSha256:hash,palette:[...document.querySelectorAll('[data-material]')].map(e=>[1,3,5].map(i=>parseInt(e.value.slice(i,i+2),16)))};await api('projects/'+project.id+'/paint-profile','POST',fit);project=await api('projects/'+project.id+'/run/clean-paint','POST');render();}catch(e){toast(e.message);}};
$('#paint-fit-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const fit=JSON.parse(await file.text());project=await api('projects/'+project.id+'/paint-profile','POST',fit);fit.palette.forEach((rgb,i)=>document.querySelector('[data-material="'+i+'"]').value='#'+rgb.map(v=>Math.round(v).toString(16).padStart(2,'0')).join(''));$('#paint-fit-status').textContent='Material regions saved for this model.';render();}catch(e){toast(e.message);}finally{e.target.value='';}};
