import {ModelPreview} from '/js/asset-model-viewer.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let config,project,view='art',modelURL='',toastTimer,saveTimer,dirty=false;const preview=new ModelPreview($('#model-canvas'),{contourMode:'silhouette'});
window.STUDIO_REVIEW={preview};
document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{preview.yaw=+b.dataset.camera;preview.pitch=.05;preview.draw();});
async function api(path,method='GET',body){const r=await fetch('/api/'+path,{method,headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.detail||'Request failed');return data;}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);}
async function safe(fn){try{return await fn();}catch(e){toast(e.message);}}
function url(name){return '/files/projects/'+project.id+'/'+encodeURIComponent(name);}
async function refreshList(){const rows=await api('projects');$('#projects').innerHTML=rows.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');if(project)$('#projects').value=project.id;return rows;}
async function load(id){await flush();project=await api('projects/'+id);localStorage.setItem('asset-studio-project',id);$('#name').value=project.name;$('#description').value=project.description;$('#style').value=project.style;view=project.animation?'animation':project.paint?'paint':project.mesh?'mesh':'art';modelURL='';render();}
async function flush(){clearTimeout(saveTimer);if(!dirty||!project)return;const p=await api('projects/'+project.id,'PUT',{name:$('#name').value,description:$('#description').value,style:$('#style').value});project=p;dirty=false;await refreshList();render();}
function changed(){dirty=true;clearTimeout(saveTimer);saveTimer=setTimeout(()=>safe(flush),650);}
for(const id of ['name','description','style'])$('#'+id).addEventListener('input',changed);
function button(text,action,primary=false){return `<button data-action="${action}" class="${primary?'primary':''}">${text}</button>`;}
function render(){if(!project)return;const busy=['queued','running'].includes(project.status),name=project[view];$('#asset-title').textContent=project.name;$('#cancel').hidden=!busy;$('#busy').hidden=!busy;$('#busy-stage').textContent=project.stage+' / '+project.message;$('#status-title').textContent=project.status==='error'?'Job needs attention':project.status==='approved'?'Approved':busy?'Local job in progress':view==='art'?'Review the concept':view==='animation'?'Review the complete motion':view==='polished'?'Production package':'Inspect the model';$('#status-message').textContent=project.message;$('#generate').disabled=busy;for(const id of ['name','description','style','upload'])$('#'+id).disabled=busy;
 $('#use-reference').hidden=busy||!project.references.length;$('#references').innerHTML=project.references.map((n,i)=>`<figure><img src="${url(n)}" alt="Reference ${i+1}"><button data-remove="${i}" aria-label="Remove reference ${i+1}" ${busy?'disabled':''}>×</button></figure>`).join('');
 document.querySelectorAll('[data-view]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.view===view);b.disabled=b.dataset.view!=='art'&&!project[b.dataset.view];});
 $('#art-preview').hidden=view!=='art'||!name;$('#model-canvas').hidden=view==='art'||!name;$('#viewer-controls').hidden=view==='art'||!name;$('#empty').hidden=!!name;
 if(view==='art'&&name){const target=url(name);if($('#art-preview').getAttribute('src')!==target)$('#art-preview').src=target;preview.pauseRendering(true);}
 else if(name){preview.pauseRendering(false);if(modelURL!==name){modelURL=name;preview.load(url(name)).then(clips=>{$('#clips').innerHTML=clips.length?clips.map(c=>`<option>${esc(c)}</option>`).join(''):'<option>No animation</option>';$('#clips').disabled=!clips.length;$('#play').disabled=!clips.length;$('#scrub').disabled=!clips.length;preview.surfaceMode($('#surface-mode').value);preview.focus($('#focus-part').value);}).catch(e=>toast(e.message));}}
 if(!name)preview.pauseRendering(true);let actions='';if(!busy){if(view==='art'&&project.art){actions+=button(project.approvals.art?'2D approved':'Approve 2D','approve-art');if(project.approvals.art)actions+=button('Make model','mesh',true)+button('Run through motion','production');}else if(view==='mesh'&&project.mesh)actions=button('Paint model','paint',true)+button('Prepare motion','animation');else if(view==='paint')actions=button('Prepare motion','animation',true);else if(view==='animation'&&project.animation){actions=button(project.approvals.animation?'Animation approved':'Approve animation','approve-animation');if(project.approvals.animation)actions+=button('Polish & package','polish',true);}else if(view==='polished'&&project.polished)actions=`<a class="download" href="/api/projects/${project.id}/export">Download asset package ↓</a>`;}if(!busy&&project.refinementProfile&&['paint','animation'].includes(view))actions+=button('Refine Vey paint & boots','refine');$('#actions').innerHTML=actions;
 const currentFile=project[view],qr=project.quality?.[view]?.file===currentFile?project.quality[view]:null;$('#quality-panel').hidden=!currentFile||view==='art';$('#validate-model').disabled=busy;$('#quality-report').innerHTML=qr?`<p><strong>${qr.status==='fail'?'Needs correction':'Technical checks complete; visual review pending'}</strong></p><ul>${qr.checks.map(c=>`<li>${c.status==='pass'?'✓':'×'} ${esc(c.name)}</li>`).join('')}</ul><p class="hint">Checks cannot certify likeness or good animation. Compare the reference, inspect every side and watch complete clips.</p><a href="${url(qr.reportFile)}" download>Download full report</a>`:'<p>Run checks on this exact file before continuing.</p>';$('#downloads').innerHTML=['art','mesh','paint','animation','polished'].filter(k=>project[k]).map(k=>`<a href="${url(project[k])}" download>${esc(k)} / ${esc(project[k])} ↓</a>`).join('');const attempts=project.timings||[];$('#timings').innerHTML=attempts.length?'<h3>Step timings</h3><p class="hint">Execution time, including failures. Approval and queue waits are separate.</p><ul>'+attempts.map(t=>`<li>${esc(t.stage)} · ${t.seconds===undefined?'running':t.seconds.toFixed(1)+' s'} · ${esc(t.status)}</li>`).join('')+`</ul><a href="${url('timings.json')}" download>Download timing receipts</a>`:'';$('#events').textContent=(project.events||[]).slice(-12).map(e=>new Date(e.time*1000).toLocaleTimeString()+' '+e.text).join('\n');}
async function run(stage){await flush();project=await api(`projects/${project.id}/run/${stage}`,'POST');view=stage==='concept'?'art':stage==='polish'?'polished':stage==='production'?'mesh':stage==='refine'?'animation':stage;render();}
$('#actions').onclick=e=>safe(async()=>{const action=e.target.closest('[data-action]')?.dataset.action;if(!action)return;if(action.startsWith('approve-')){await flush();project=await api(`projects/${project.id}/approve/${action.slice(8)}`,'POST');render();}else await run(action);});
$('#validate-model').onclick=()=>safe(async()=>{project=await api(`projects/${project.id}/validate/${view}`,'POST');render();});
$('#use-reference').onclick=()=>safe(async()=>{await flush();project=await api(`projects/${project.id}/use-reference/0`,'POST');view='art';render();});
$('#generate').onclick=()=>safe(()=>run('concept'));$('#cancel').onclick=()=>safe(async()=>{const r=await api(`projects/${project.id}/cancel`,'POST');toast(r.message);});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});
$('#projects').onchange=e=>safe(()=>load(e.target.value));$('#new').onclick=()=>safe(async()=>{await flush();project=await api('projects','POST',{name:'Untitled asset'});await refreshList();await load(project.id);$('#name').focus();$('#name').select();});
async function upload(file){await flush();const data=new FormData();data.append('file',file);project=await api(`projects/${project.id}/upload`,'POST',data);if(file.name.toLowerCase().endsWith('.glb'))view='mesh';render();}
$('#upload').onchange=e=>safe(async()=>{if(e.target.files[0])await upload(e.target.files[0]);e.target.value='';});
$('#paste-area').addEventListener('paste',e=>{const files=[...e.clipboardData.items].filter(i=>i.kind==='file'&&i.type.startsWith('image/')).map(i=>i.getAsFile());if(files.length){e.preventDefault();safe(async()=>{for(const f of files)await upload(f);});}});
$('#references').onclick=e=>safe(async()=>{const button=e.target.closest('[data-remove]');if(button){project=await api(`projects/${project.id}/references/${button.dataset.remove}`,'DELETE');render();}});
$('#clips').onchange=e=>preview.clip(e.target.value,{fade:.22});$('#focus-part').onchange=e=>preview.focus(e.target.value);$('#surface-mode').onchange=e=>preview.surfaceMode(e.target.value);$('#scrub').oninput=e=>{preview.seek(+e.target.value);$('#play').textContent='Play';};$('#play').onclick=()=>{$('#play').textContent=preview.toggle()?'Pause':'Play';};$('#speed').oninput=e=>preview.speed=+e.target.value;$('#contour').oninput=e=>preview.ink(+e.target.value);$('#reset-view').onclick=()=>preview.reset();
function fillSettings(){const s=config.settings;for(const id of ['meshEngine','paintEngine']){$('#'+id).value=s[id];$('#'+id+' option[value=trellis2]').disabled=!config.trellisReady;}$('#trellis-status').textContent=config.trellisReady?'Trellis has completed a local trial. Each result still needs visual review.':'Trellis installation and trial have not been verified yet.';$('#model').innerHTML=config.models.map(m=>`<option value="${esc(m.family+'|'+m.name)}">${esc(m.name)}</option>`).join('')||'<option>No complete model installed yet</option>';if(config.models.length)$('#model').value=s.family+'|'+s.model;$('#save-settings').disabled=!config.models.length;for(const id of ['width','height','steps','seed','meshSteps','meshResolution','textureSize','trellisSteps'])$('#'+id).value=s[id];$('#loras').innerHTML=config.loras.map(name=>{const chosen=s.loras.find(l=>l.name===name);return `<div class="lora-row"><input type="checkbox" data-lora="${esc(name)}" aria-label="Enable ${esc(name)}" ${chosen?'checked':''}><label>${esc(name)}</label><input type="number" aria-label="${esc(name)} strength" value="${chosen?.strength??.7}" min="-2" max="2" step=".05"></div>`;}).join('')||'<p class="hint">No LoRAs installed yet.</p>';$('#paths').textContent='Weights: '+config.paths.models+'\nAssets: '+config.paths.projects;$('#model-summary').textContent=s.model.replace('.safetensors','')+' / '+s.width+' × '+s.height;}
$('#settings-open').onclick=()=>safe(async()=>{config=await api('config');fillSettings();$('#settings').showModal();});$('#rescan').onclick=()=>safe(async()=>{config=await api('config');fillSettings();toast('Installed models refreshed');});
$('#save-settings').onclick=()=>safe(async()=>{const [family,model]=$('#model').value.split('|');const s={family,model,meshEngine:$('#meshEngine').value,paintEngine:$('#paintEngine').value,loras:[...document.querySelectorAll('[data-lora]:checked')].map(e=>({name:e.dataset.lora,strength:+e.closest('.lora-row').querySelector('input[type=number]').value}))};for(const id of ['width','height','steps','seed','meshSteps','meshResolution','textureSize','trellisSteps'])s[id]=+$('#'+id).value;config=await api('config','PUT',s);fillSettings();$('#settings').close();toast('Local settings saved');});
$('#start-engine').onclick=()=>safe(async()=>{const r=await api('runtime/start','POST');toast(r.message);});
async function health(){const s=await api('status');$('#engine-dot').className=s.comfy?'ready':'';$('#engine-label').textContent=s.comfy?'Engine ready':'Engine stopped';$('#engine-note').hidden=s.comfy;$('#hardware').textContent=s.gpu?`${s.gpu.name} / ${Math.round(s.gpu.free/1024*10)/10} GB free of ${Math.round(s.gpu.total/1024)} GB. One worker runs at a time.`:'GPU information unavailable.';}
await safe(async()=>{config=await api('config');$('#style').innerHTML=config.styles.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');fillSettings();const rows=await refreshList();if(!rows.length)project=await api('projects','POST',{name:'My first asset'});const stored=localStorage.getItem('asset-studio-project');await load(rows.find(p=>p.id===stored)?.id||rows[0]?.id||project.id);await refreshList();await health();});
setInterval(()=>safe(async()=>{if(!project||dirty)return;const latest=await api('projects/'+project.id);if(latest.updated!==project.updated){const wasBusy=['running','queued'].includes(project.status);project=latest;if(wasBusy&&!['running','queued'].includes(project.status)){view=project.polished?'polished':project.animation?'animation':project.paint?'paint':project.mesh?'mesh':'art';await refreshList();}render();}}),1800);setInterval(()=>safe(health),15000);
