import * as THREE from '/lib/three.module.min.js';
import {ModelPreview} from '/js/asset-model-viewer.js';
const $=s=>document.querySelector(s),id=new URL(location.href).searchParams.get('project'),base='/api/projects/'+encodeURIComponent(id),canvas=$('canvas'),viewer=new ModelPreview(canvas,{contourMode:'silhouette'});
viewer.pauseRendering(true);$('#back').href='/?project='+encodeURIComponent(id);
let profile,project,mode='front',height=2,center=new THREE.Vector3(0,1,0),camera=new THREE.OrthographicCamera(),markers=new THREE.Group();viewer.scene.add(markers);
const world=a=>new THREE.Vector3(a[0],a[2],-a[1]),coords=v=>[v.x,-v.z,v.y].map(x=>Math.round(x*1000)/1000);
function draft(sha,h){const joints=[],add=(name,head,tail,parent)=>joints.push({name,head:head.map(x=>x*h/2),tail:tail.map(x=>x*h/2),parent});
 add('root',[0,0,0],[0,0,.1],null);add('hips',[0,0,.93],[0,0,1.05],'root');add('spine',[0,0,1.05],[0,0,1.27],'hips');add('chest',[0,0,1.27],[0,0,1.52],'spine');add('neck',[0,0,1.52],[0,0,1.7],'chest');add('head',[0,0,1.7],[0,0,1.98],'neck');
 for(const [side,k]of [['L',1],['R',-1]]){const v=(x,y,z)=>[x*k,y,z];add('clavicle.'+side,[0,0,1.48],v(.29,0,1.47),'chest');add('upper_arm.'+side,v(.29,0,1.47),v(.43,0,1.16),'clavicle.'+side);add('forearm.'+side,v(.43,0,1.16),v(.51,0,.9),'upper_arm.'+side);add('hand.'+side,v(.51,0,.9),v(.53,-.03,.74),'forearm.'+side);add('thigh.'+side,v(.17,0,.96),v(.2,0,.57),'hips');add('shin.'+side,v(.2,0,.57),v(.2,0,.15),'thigh.'+side);add('foot.'+side,v(.2,0,.15),v(.2,-.16,.08),'shin.'+side);add('toe.'+side,v(.2,-.16,.08),v(.2,-.27,.07),'foot.'+side);}
 return {name:'Fitted biped draft',sourceSha256:sha,coordinateSystem:'Blender metres, Z up, -Y front',joints,preserveRestDirection:['head','hand.L','hand.R'],footRoll:true,ownerApproved:false};}
function selected(){return profile.joints.find(j=>j.name===$('#joint').value);}
function updateFields(){const a=selected()[$('#endpoint').value];['x','y','z'].forEach((n,i)=>$('#'+n).value=a[i]);draw();}
function move(next){const joint=selected(),key=$('#endpoint').value,old=joint[key].slice();for(const j of profile.joints)for(const e of ['head','tail'])if(j[e].every((x,i)=>Math.abs(x-old[i])<.0001))j[e]=next.slice();
 if($('#mirror').checked&&/\.[LR]$/.test(joint.name)){const other=profile.joints.find(j=>j.name===joint.name.replace(/\.([LR])$/,(_,s)=>'.'+(s==='L'?'R':'L')));if(other){const prior=other[key].slice(),mirrored=[-next[0],next[1],next[2]];for(const j of profile.joints)for(const e of ['head','tail'])if(j[e].every((x,i)=>Math.abs(x-prior[i])<.0001))j[e]=mirrored.slice();}}
 updateFields();}
function draw(){if(!profile)return;while(markers.children.length){const o=markers.children[0];markers.remove(o);o.geometry?.dispose();o.material?.dispose();}
 for(const j of profile.joints){const active=j.name===$('#joint').value,points=[world(j.head),world(j.tail)],line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:active?0xd64519:0x007266,depthTest:false}));line.renderOrder=20;markers.add(line);for(const [i,point]of points.entries()){const dot=new THREE.Mesh(new THREE.SphereGeometry(height*(active?.009:.005),8,6),new THREE.MeshBasicMaterial({color:active&&i===($('#endpoint').value==='head'?0:1)?0xff6a20:0x007266,depthTest:false}));dot.position.copy(point);dot.renderOrder=21;markers.add(dot);}}
 const w=canvas.clientWidth,h=canvas.clientHeight;viewer.renderer.setSize(w,h,false);const half=height*.64;camera.left=-half*w/h;camera.right=half*w/h;camera.top=half;camera.bottom=-half;camera.near=.01;camera.far=100;camera.position.copy(center).add(new THREE.Vector3(...(mode==='side'?[6,0,0]:mode==='back'?[0,0,-6]:[0,0,6])));camera.lookAt(center);camera.updateProjectionMatrix();viewer.renderer.render(viewer.scene,camera);}
try{project=await fetch(base).then(r=>r.json());const file=project.paint||project.mesh;if(!file)throw Error('Create a model first');const path='/files/projects/'+id+'/'+file,bytes=await fetch(path).then(r=>r.arrayBuffer()),sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');await viewer.load(path);viewer.playing=false;viewer.mixer.stopAllAction();height=viewer.height;center.copy(viewer.target);
 profile=project.rigProfile?await fetch('/files/projects/'+id+'/'+project.rigProfile.file).then(r=>r.json()):draft(sha,height);if(profile.sourceSha256!==sha)throw Error('Saved fit belongs to a different model. Archive it in Studio first.');$('#joint').innerHTML=profile.joints.map(j=>'<option>'+j.name+'</option>').join('');$('#yaw').value=profile.sourceYawDegrees||0;viewer.root.rotation.y=THREE.MathUtils.degToRad(profile.sourceYawDegrees||0);viewer.root.position.add(world(profile.sourceOffset||[0,0,0]));center.add(world(profile.sourceOffset||[0,0,0]));$('#status').textContent=project.rigProfile?'Editing the current model fit.':'Starting from a biped draft. Fit every joint before motion.';updateFields();
}catch(e){$('#status').textContent=e.message;}
$('#joint').onchange=$('#endpoint').onchange=updateFields;document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{mode=b.dataset.camera;draw();});for(const n of ['x','y','z'])$('#'+n).onchange=()=>move(['x','y','z'].map(k=>+$('#'+k).value));
$('#yaw').onchange=e=>{profile.sourceYawDegrees=+e.target.value;viewer.root.rotation.y=THREE.MathUtils.degToRad(profile.sourceYawDegrees);draw();};
canvas.addEventListener('pointerdown',e=>{if(!profile)return;const rect=canvas.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const old=world(selected()[$('#endpoint').value]),normal=new THREE.Vector3(...(mode==='side'?[1,0,0]:[0,0,1])),point=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane().setFromNormalAndCoplanarPoint(normal,old),point))move(coords(point));});
$('#save').onclick=async()=>{try{const r=await fetch(base+'/rig-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}),data=await r.json();if(!r.ok)throw Error(data.detail);$('#status').textContent='Fit saved. Return to Studio and prepare motion.';}catch(e){$('#status').textContent=e.message;}};new ResizeObserver(draw).observe(canvas);
