import {ModelPreview} from '/js/asset-model-viewer.js';
const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=new URL(location.href).searchParams.get('project');
const preview=new ModelPreview($('canvas'),{contourMode:'silhouette'});window.MOTION_REVIEW={preview};
let state,selected=null,shown='',lastUpdate=0;
function fit(){const box=$('canvas').getBoundingClientRect();if(preview.height&&box.width)preview.distance=preview.height*Math.max(2.4,1.9*box.height/box.width);}
window.addEventListener('resize',fit);
async function api(path,body){const r=await fetch('/api/projects/'+key+'/'+path,{method:body===undefined?'GET':'POST',headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');return d;}
async function safe(fn){try{await fn();}catch(e){$('#message').textContent=e.message;}}
const url=name=>'/files/projects/'+key+'/'+name.split('/').map(encodeURIComponent).join('/');
function options(){const method=$('#method').value;$('#motion-fields').hidden=method!=='mixamo';$('#method-note').textContent=method==='mixamo'?'Captured movement, fitted boot contact and loop continuity. Choose a walk or run.':method==='mia'?'Predicts 52 humanoid bones and skin weights. Unusual alien anatomy or extra tails may fail the checks; your fitted rig stays available.':'Generates six views, geometry and UV paint locally. Inspect silhouette and fine details against the current Modly model.';$('#generate').disabled=!state?.engines[method]||['queued','running'].includes(state?.project.status);}
async function show(item){selected=item;$('#reviewed').checked=false;const p=state.project,file=item?item.file:(p.animation||p.paint||p.mesh);$('canvas').hidden=!file;preview.pauseRendering(!file);$('#title').textContent=item?({mixamo:'Mixamo locomotion',mia:'MIA rig',instantmesh:'InstantMesh shape'}[item.method]||item.method):'Current fitted model';$('#review-source').textContent=item?.message||'Current selected asset. Drag to orbit, inspect hands and boots, and compare paint with the unlit surface.';$('#checks').innerHTML='';$('#choose').hidden=!item?.passed||item.method==='mia';$('#receipt').hidden=!item?.report;$('#receipt').href=item?.report?url(item.report):'';$('#views-wrap').hidden=item?.method!=='instantmesh'||!file;
 if(item?.method==='instantmesh'&&file)$('#views').src=url(file.replace(/\.glb$/,'.views.png'));
 let reviewedClip;
 if(item?.report){const r=await fetch(url(item.report)).then(r=>r.json());reviewedClip=r.clip;const failures=(r.checks||[]).filter(c=>c.status==='fail');if(failures.length)$('#review-source').textContent='Needs correction: '+failures.map(c=>c.name).join(', ')+'. Current asset retained.';$('#checks').innerHTML=(r.checks||[]).map(c=>`<li>${c.status==='pass'?'Pass':'Needs work'} · ${escape(c.name)}<br><span class="hint">${escape(c.detail)}</span></li>`).join('');}
 if(file&&shown!==file){shown=file;const clips=await preview.load(url(file));$('#clip').innerHTML=clips.map(c=>`<option value="${escape(c)}">${escape(c.replace(/^Mixamo (?:Mixamo )?/,'Captured · '))}</option>`).join('');const preferred=clips.includes(reviewedClip)?reviewedClip:clips.find(c=>c.includes('Mixamo'))||clips[0];if(preferred){preview.clip(preferred);$('#clip').value=preferred;}$('#play').disabled=$('#scrub').disabled=!clips.length;preview.surfaceMode($('#surface').value);fit();preview.pauseRendering(false);}window.MOTION_REVIEW.ready=true;
}
async function refresh(){state=await api('research');const p=state.project;$('#back').href='/?project='+key;$('#message').textContent=p.message;$('#reference').src=p.art?url(p.art):'';$('#reference').hidden=!p.art;const chosen=$('#motion').value;$('#motion').innerHTML=state.motions.map(m=>`<option value="${escape(m.id)}">${escape(m.name||m.label||m.id)}</option>`).join('')||'<option value="">Import a capture first</option>';if(state.motions.some(m=>m.id===chosen))$('#motion').value=chosen;
 const target=$('#target').value;$('#target').innerHTML='<option value="">Current fitted rig</option>'+(p.researchCandidates||[]).filter(c=>c.passed&&['mia','mixamo'].includes(c.method)).map(c=>`<option value="${c.id}">${escape(c.method)} · ${new Date(c.createdAt*1000).toLocaleTimeString()}</option>`).join('');$('#target').value=target;
 $('#candidates').innerHTML='<button data-candidate="">Current asset</button>'+(p.researchCandidates||[]).slice().reverse().map(c=>`<button data-candidate="${c.id}" aria-pressed="${selected?.id===c.id}">${escape(c.method)} · ${escape(c.status)}<br><span class="hint">${new Date(c.createdAt*1000).toLocaleTimeString()}</span></button>`).join('');$('#timings').innerHTML=(p.timings||[]).map(t=>`<li>${escape(t.stage)} · ${t.seconds===undefined?'running':t.seconds.toFixed(2)+' s'} · ${escape(t.status)}</li>`).join('');$('#import').disabled=['queued','running'].includes(p.status);options();captureInfo();
 if(!shown)await show(null);if(selected&&p.updated!==lastUpdate){const updated=p.researchCandidates.find(c=>c.id===selected.id);if(updated)await show(updated);}lastUpdate=p.updated;
}
function captureInfo(){const m=state?.motions.find(m=>m.id===$('#motion').value);$('#capture-info').textContent=m?`${m.sourceFps||m.fps||'?'} FPS · ${m.frames||m.frameCount||'?'} frames · original capture retained`:'';}
$('#method').onchange=options;$('#motion').onchange=captureInfo;$('#generate').onclick=()=>safe(async()=>{await api('research',{method:$('#method').value,motion:$('#motion').value,target:$('#target').value});await refresh();});$('#import').onclick=()=>safe(async()=>{const file=$('#import-file').files[0];if(!file)throw Error('Choose a local Mixamo FBX first.');const body=new FormData();body.append('file',file);await api('motion-library',body);$('#import-file').value='';await refresh();});
$('#candidates').onclick=e=>safe(async()=>{const b=e.target.closest('[data-candidate]');if(b)await show(state.project.researchCandidates?.find(c=>c.id===b.dataset.candidate)||null);});$('#use').onclick=()=>safe(async()=>{if(!$('#reviewed').checked)throw Error('Inspect the candidate and confirm visual review first.');await api('research/'+selected.id+'/use',{visualReviewConfirmed:true});location.href='/?project='+key;});
$('#clip').onchange=()=>{preview.clip($('#clip').value);$('#play').textContent='Pause';};$('#play').onclick=()=>$('#play').textContent=preview.toggle()?'Pause':'Play';$('#scrub').oninput=()=>{preview.seek(+$('#scrub').value);$('#play').textContent='Play';};$('#surface').onchange=()=>preview.surfaceMode($('#surface').value);document.querySelectorAll('[data-yaw]').forEach(b=>b.onclick=()=>{preview.yaw=+b.dataset.yaw;preview.draw();});
await safe(refresh);setInterval(()=>safe(refresh),2200);
