import * as THREE from 'three';
import {createSurfaceMaterials,GRAPHICS_DEFAULTS,GRAPHICS_LIMITS,normalizeGraphics} from './arena-materials.js';
import {createWorlds,navigation} from './arena-world.js';
import {GRAPHICS_PRESETS,matchingPreset,ART_DIRECTION_VERSION} from './arena-presets.js';
import {newHandling,updateHandling} from './arena-handling.js';
import {SWORD_DURATIONS} from './arena-motion.js';
import {createWeapons} from './arena-weapons.js';
import {kit} from './arena-kit.js';
import {createVeyActor,VEY_PACE} from './arena-vey.js';
import {createDemoUnit} from './arena-unit.js';
import {createEffects,plasmaMesh} from './arena-effects.js';
import {UNIT_TYPES,newRound,beginRound,advanceRound,registerKill,segmentDistanceSquared,swordActive} from './arena-rules.js';

const $=s=>document.querySelector(s),canvas=$('#world'),reduced=matchMedia('(prefers-reduced-motion: reduce)'),up=new THREE.Vector3(0,1,0);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(78,1,.08,170),handsScene=new THREE.Scene(),handsCamera=new THREE.PerspectiveCamera(65,1,.025,10);
camera.layers.enable(1);handsCamera.layers.enable(1);camera.rotation.order='YXZ';
const sun=new THREE.DirectionalLight('#ffe6b8',2.1);sun.position.set(-13,24,13);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-29,right:29,top:29,bottom:-29,near:1,far:85});sun.shadow.bias=-.0001;sun.shadow.normalBias=.035;sun.shadow.blurSamples=8;
const ambient=new THREE.HemisphereLight('#e2ebdc','#83765f',1.15),fill=new THREE.DirectionalLight('#bdced7',.35);fill.position.set(15,10,-15);scene.add(sun,ambient,fill);
const handSun=new THREE.DirectionalLight('#ffe6b8',2.1);handSun.position.set(-3,5,4);handsScene.add(handSun,new THREE.HemisphereLight('#e2ebdc','#83765f',1.15));
const state={world:'meadow',weapon:'sword',camera:new URLSearchParams(location.search).get('camera')==='first'?'first':'third',flight:false,playing:false,paused:true,hits:0,shots:0,swings:0,guards:0,muted:false};
const player={position:new THREE.Vector3(0,0,11),velocity:new THREE.Vector3(),health:100,vertical:0,jump:0,invulnerable:0,respawn:0};
const handling=newHandling(),graphics={...GRAPHICS_DEFAULTS},round=newRound(),keys=new Set(),enemies=[],towers=[],bolts=[],events=[],timings=[],stick={x:0,y:0};
let renderer,paint,worlds,world,nav,hero,heroGear,rig,fx,k,ready=false,lost=false,time=0,last=performance.now(),yaw=0,pitch=0,attackTime=0,attackDuration=.62,combo=-1,attackQueued=false,attackHeld=false,aim=false,shotDelay=0,heat=0,vent=0,hitMark=0,damageMark=0,shake=0,look=[0,0],stride=0,stepDistance=0,uiTimer=0,noticeTime=0,manual=false,touchRun=false,drag=null,stickPointer=null,audioContext;
const swordHits=new Set(),previousTip=new THREE.Vector3(),previousBase=new THREE.Vector3(),trail=[],desired=new THREE.Vector3(),forward=new THREE.Vector3(),from=new THREE.Vector3(),to=new THREE.Vector3();
const event=(kind,data={})=>{events.push({time,...data,kind});if(events.length>800)events.shift();};
function notice(text,seconds=2.5){$('#notice').textContent=text;noticeTime=seconds;}
function sound(kind){if(state.muted||!audioContext||audioContext.state!=='running')return;const a=audioContext,t=a.currentTime,g=a.createGain(),o=a.createOscillator();o.type=kind==='plasma'?'triangle':'sine';const notes={plasma:[620,140,.10,.025],hit:[180,45,.12,.035],sword:[260,70,.14,.022],step:[65,35,.045,.018],guard:[800,340,.17,.025]},n=notes[kind]||notes.hit;o.frequency.setValueAtTime(n[0],t);o.frequency.exponentialRampToValueAtTime(n[1],t+n[2]);g.gain.setValueAtTime(n[3],t);g.gain.exponentialRampToValueAtTime(.0001,t+n[2]);o.connect(g);g.connect(a.destination);o.start(t);o.stop(t+n[2]);}
function clearInput(){keys.clear();attackHeld=attackQueued=aim=false;stick.x=stick.y=0;drag=null;stickPointer=null;$('#thumb').style.transform='';}
function pause(value){state.paused=value;clearInput();last=performance.now();}
function enter(){if(!ready||lost)return;state.playing=true;pause(false);$('#entry').hidden=true;$('#settings').hidden=$('#controls').hidden=true;$('#graphics').setAttribute('aria-expanded','false');$('#help').setAttribute('aria-expanded','false');canvas.focus();try{audioContext||=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();}catch{/* Sound is optional. */}if(!matchMedia('(pointer: coarse)').matches){try{const lock=canvas.requestPointerLock();lock?.catch(()=>notice('Click to attack. Drag to look. J holds an attack.',5));}catch{notice('Click to attack. Drag to look. J holds an attack.',5);}}}
function overlay(id,visible){const panel=$(id);panel.hidden=!visible;if(visible){pause(true);$('#entry').hidden=true;document.exitPointerLock?.();panel.querySelector('button')?.focus();}else{$('#entry-title').textContent='Ready when you are.';$('#enter').textContent='Resume exploring';$('#entry').hidden=false;}$('#graphics').setAttribute('aria-expanded',String(!$('#settings').hidden));$('#help').setAttribute('aria-expanded',String(!$('#controls').hidden));}
function chooseWeapon(name){if(!['sword','rifle'].includes(name))return;state.weapon=name;attackTime=0;attackQueued=false;swordHits.clear();trail.forEach(t=>t.mesh.visible=false);document.querySelectorAll('[data-weapon]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.weapon===name)));event('equip',{weapon:name});}
function toggleFlight(){state.flight=!state.flight;Object.assign(handling,newHandling());player.vertical=0;player.jump=0;if(state.flight)player.position.y+=1;else player.position.y=world.height(player.position.x,player.position.z);player.velocity.set(0,0,0);$('#fly').textContent=state.flight?'F · Land':'F · Fly';notice(state.flight?'Flight · Space up / Ctrl down · Shift faster':'Ground movement');event('flight',{enabled:state.flight});}
function toggleCamera(){state.camera=state.camera==='first'?'third':'first';$('#camera').textContent=state.camera==='first'?'V · Third person':'V · First person';event('camera',{mode:state.camera});}
function leap(){if(!state.paused&&!state.flight&&player.jump<=0&&player.respawn<=0){player.vertical=7;handling.slide=0;handling.cooldown=.35;hero.action('Jump',.8);event('jump');}}
function startVent(){if(state.weapon==='rifle'&&heat>.01&&!vent){vent=1;notice('Venting plasma',1);event('vent');}}
function applyGraphics(input){Object.assign(graphics,normalizeGraphics(input));for(const [name,value] of Object.entries(graphics)){const slider=$('#g-'+name);if(slider){slider.value=value;slider.nextElementSibling.value=Number(value.toFixed(name==='fog'?4:3));}}if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,2)*graphics.resolution);renderer.toneMappingExposure=graphics.exposure;}if(ready)updateCamera();const selected=matchingPreset(graphics);document.querySelectorAll('[data-preset]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.preset===selected)));return {...graphics};}
const labels={line:'Black contour thickness',fog:'Atmospheric haze',shadowDepth:'Shadow depth',saturation:'Color saturation',texture:'Painted surface texture',exposure:'Exposure',resolution:'Render scale',fov:'Field of view',bob:'Movement sway',shake:'Impact motion',sensitivity:'Mouse sensitivity'};
for(const [name,[min,max]] of Object.entries(GRAPHICS_LIMITS)){const label=document.createElement('label');label.htmlFor='g-'+name;label.textContent=labels[name];const row=document.createElement('div'),slider=document.createElement('input'),output=document.createElement('output');slider.type='range';slider.id='g-'+name;slider.min=min;slider.max=max;slider.step=name==='fog'?.0005:name==='fov'?1:.01;slider.value=graphics[name];output.htmlFor=slider.id;output.value=graphics[name];slider.oninput=()=>{applyGraphics({...graphics,[name]:Number(slider.value)});$('#preset-status').textContent='Custom session settings. Locked 1.3.2 reference is unchanged.';};row.append(slider,output);label.append(row);$('#sliders').append(label);}
function resetPlayer(){Object.assign(handling,newHandling());player.position.set(0,world.height(0,11),11);player.velocity.set(0,0,0);player.health=100;player.jump=player.vertical=player.respawn=0;player.invulnerable=2;attackTime=heat=vent=shotDelay=0;combo=-1;attackQueued=false;hero.reset();yaw=pitch=0;}
function resetArena(){clearInput();Object.assign(round,newRound());state.hits=state.swings=state.shots=state.guards=0;resetPlayer();state.flight=false;$('#fly').textContent='F · Fly';fx.clear();for(const b of bolts)b.life=0;enemies.forEach(e=>{e.active=false;e.actor.root.visible=false;});spawn(3,true);noticeTime=0;$('#notice').style.opacity=0;$('#hitmarker').style.opacity=0;$('#damage').style.opacity=0;hitMark=damageMark=shake=0;updateCamera();rig.update(.2,{weapon:state.weapon});ui();event('reset');}
function selectWorld(id){if(!ready)return;world=worlds.find(w=>w.id===id)||worlds[0];state.world=world.id;worlds.forEach(w=>w.root.visible=w===world);nav=navigation(world);scene.background=new THREE.Color(world.sky);scene.fog=new THREE.FogExp2(world.sky,graphics.fog);sun.color.set(world.sun);ambient.color.set(world.ambient);handSun.color.set(world.sun);$('#world-name').textContent=world.name;document.querySelectorAll('[data-world]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.world===world.id)));for(const [i,t] of towers.entries()){const positions=[[-7,9],[7,7],[0,15]],p=positions[i];t.root.position.set(p[0],world.height(...p),p[1]);}resetArena();history.replaceState(null,'',location.pathname+'?world='+world.id);event('environment',{id:world.id});}
function startRound(){if(!ready)return;resetPlayer();for(const e of enemies){e.active=false;e.actor.root.visible=false;}for(const b of bolts)b.life=0;beginRound(round);ui();notice('Demo round · Three waves · Infinite lives',3);event('round-start');}
function spawn(count,tour=false){for(let i=0;i<count;i++){const e=enemies[i];e.type=UNIT_TYPES[i%3];const angle=(i/count)*Math.PI*2+.4,x=tour?[-3,4,1][i]:Math.sin(angle)*14,z=tour?[5,1,-5][i]:Math.cos(angle)*12-2;e.active=true;e.reappear=0;e.tour=tour;e.hp=e.type.hp;e.dead=0;e.cooldown=.8+i*.3;e.path=[];e.pathTime=0;e.actor.root.visible=true;e.actor.root.scale.setScalar(1);let sx=x,sz=z;for(let n=1;world.blocked(sx,sz,.85)&&n<100;n++){const a=n*2.399,r=.6*Math.sqrt(n);sx=x+Math.cos(a)*r;sz=z+Math.sin(a)*r;}e.actor.root.position.set(sx,world.height(sx,sz),sz);e.home=e.actor.root.position.clone();e.actor.reset();e.velocity.set(0,0,0);e.hit=0;e.actor.root.rotation.y=Math.PI;e.targetAngle=Math.PI;}event(tour?'patrols':'wave-spawn',{count,wave:round.wave});}
function enemyHit(e,amount,source){if(!e.active||e.dead>0)return;e.hp-=amount;e.hit=.18;state.hits++;hitMark=.18;shake=Math.max(shake,.045);const p=e.actor.root.position.clone().add(new THREE.Vector3(0,1.3,0));fx.hit(p,source==='sword'?'#f3cc86':'#9aecd5');sound('hit');event('hit',{id:e.id,source,hp:e.hp});if(e.hp<=0){e.dead=1.3;e.actor.reset();e.actor.action('Death',1.2);if(!e.tour)registerKill(round);event('kill',{id:e.id,source});}else if(source==='sword'){const push=e.actor.root.position.clone().sub(player.position).setY(0).normalize().multiplyScalar(.4),q=e.actor.root.position.clone().add(push);if(!world.blocked(q.x,q.z,.7))e.actor.root.position.copy(q);}}
function playerHit(amount,origin){if(player.invulnerable>0||player.respawn>0)return;const dir=origin.clone().sub(player.position).setY(0).normalize(),lookDir=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));if(state.weapon==='sword'&&aim&&!attackTime&&dir.dot(lookDir)>.15){amount*=.12;state.guards++;sound('guard');fx.ring(player.position.clone().add(new THREE.Vector3(0,1.4,0)),{radius:.8,life:.25,color:'#d5eab6',vertical:true});event('guard');}player.health=Math.max(0,player.health-amount);damageMark=.28;shake=.09;event('player-hit',{health:player.health});if(!player.health){player.respawn=1;round.respawns++;attackTime=0;notice('Reforming at the beacon… Infinite lives.',1);event('respawn-start');}}
function bolt(origin,direction,{owner='player',damage=24,speed=50,color='#95ead4'}={}){const b=bolts.find(b=>b.life<=0);if(!b)return false;b.mesh.visible=true;b.mesh.position.copy(origin);b.velocity.copy(direction).normalize().multiplyScalar(speed);b.life=2.4;b.owner=owner;b.damage=damage;b.mesh.material.color.set(color);b.mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.velocity.clone().normalize());b.mesh.scale.y=owner==='player'?1:.7;return true;}
function fire(){if(vent>0||shotDelay>0||player.respawn>0)return;shotDelay=.115;heat=Math.min(1,heat+.05);state.shots++;rig.fire();sound('plasma');from.copy(rig.tip).applyQuaternion(camera.quaternion).add(camera.position);camera.getWorldDirection(forward);const sightTarget=camera.position.clone().addScaledVector(forward,60);forward.copy(sightTarget).sub(from).normalize();if(state.camera==='third'){from.copy(player.position).add(new THREE.Vector3(0,1.55,0));}bolt(from,forward);fx.puff(from,{count:3,color:'#c2f5df',life:.12,size:.045,speed:.4,gravity:0,up:0});event('plasma-fire');if(heat>=1){vent=1;notice('Plasma cooling',1);}}
function pressAttack(){if(state.paused)return;if(attackTime/attackDuration>.5)attackQueued=true;attackHeld=true;if(state.weapon==='sword')beginSwing();else fire();}
function beginSwing(){if(attackTime||player.respawn>0)return;attackQueued=false;combo=(combo+1)%3;attackDuration=SWORD_DURATIONS[combo];attackTime=.0001;swordHits.clear();previousTip.set(NaN,0,0);state.swings++;hero.action('Punch',attackDuration);sound('sword');event('sword-start',{combo});}
function swordContact(){if(!swordActive(attackTime/attackDuration))return;const a=rig.base.clone().applyQuaternion(camera.quaternion).add(camera.position),b=rig.tip.clone().applyQuaternion(camera.quaternion).add(camera.position);if(state.camera==='third'){a.copy(player.position).add(new THREE.Vector3(0,1.35,0));b.copy(a).add(new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)).multiplyScalar(2.3));}if(!Number.isFinite(previousTip.x)){previousTip.copy(b);previousBase.copy(a);}for(const e of enemies){if(!e.active||e.dead||swordHits.has(e.id)||e.actor.root.position.distanceTo(player.position)>3.4)continue;const p=e.actor.root.position.clone();p.y=THREE.MathUtils.clamp((a.y+b.y)/2,p.y+.45,p.y+1.9);if(Math.min(segmentDistanceSquared(p,a,b),segmentDistanceSquared(p,previousTip,b))<.75*.75){swordHits.add(e.id);enemyHit(e,combo===2?54:42,'sword');}}fx.slash(a,b,previousBase,previousTip);previousTip.copy(b);previousBase.copy(a);}
function move(dt){
  const x=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'))+stick.x,z=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp'))+stick.y,run=keys.has('ShiftLeft')||keys.has('ShiftRight')||touchRun,crouch=keys.has('ControlLeft')||keys.has('ControlRight')||keys.has('KeyC');
  const transition=updateHandling(handling,dt,{x:player.respawn?0:x,z:player.respawn?0:z,yaw,run,crouch,aim,attack:attackHeld||attackTime>0,grounded:player.jump<=0,flight:state.flight,pace:state.camera==='third'?VEY_PACE:undefined});
  if(transition.startedSlide){event('slide-start');sound('step');}
  player.velocity.set(handling.vx,player.velocity.y,handling.vz);
  if(state.flight)player.velocity.y=THREE.MathUtils.damp(player.velocity.y,(Number(keys.has('Space'))-Number(crouch))*(run?12:6),8,dt);
  const p=player.position,old=p.clone(),nx=p.x+player.velocity.x*dt,nz=p.z+player.velocity.z*dt;
  if(state.flight){p.x=THREE.MathUtils.clamp(nx,-38,38);p.z=THREE.MathUtils.clamp(nz,-38,38);p.y=THREE.MathUtils.clamp(p.y+player.velocity.y*dt,world.height(p.x,p.z)+.3,30);}
  else{
    const bx=world.blocked(nx,p.z,.42);if(!bx)p.x=nx;else handling.vx=player.velocity.x=0;
    const bz=world.blocked(p.x,nz,.42);if(!bz)p.z=nz;else handling.vz=player.velocity.z=0;
    if((bx||bz)&&handling.slide){handling.slide=0;handling.cooldown=.35;event('slide-blocked');}
    if(player.jump>0||player.vertical>0){player.vertical-=22*dt;player.jump+=player.vertical*dt;if(player.jump<=0){handling.land=Math.min(.09,Math.abs(player.vertical)*.009);player.jump=player.vertical=0;fx.puff(p.clone(),{count:9,speed:1.2,size:.1});event('land');}}
    p.y=world.height(p.x,p.z)+player.jump;
  }
  const distance=Math.hypot(p.x-old.x,p.z-old.z),actual=distance/dt;stride+=distance*3.2;stepDistance+=distance;if(stepDistance>.95&&!state.flight&&!player.jump&&!handling.slide){stepDistance=0;sound('step');fx.puff(p.clone().add(new THREE.Vector3(0,.04,0)),{count:2,color:'#b1bba0',size:.07,life:.4,speed:.25,up:.2});}hero.root.position.copy(p);hero.root.rotation.y=yaw+Math.PI;hero.tick(dt,state.flight?0:actual);const hand=hero.hand;if(hand){hand.getWorldPosition(from);hero.root.worldToLocal(from);for(const [id,g] of Object.entries(heroGear)){g.root.visible=id===state.weapon;g.root.position.copy(from);g.root.rotation.set(id==='sword'?-.7-(attackTime?Math.sin(attackTime/attackDuration*Math.PI)*1.5:0):0,Math.PI,0);}}return actual;}
function clearSight(a,b){return !world.obstacles.some(([x,z,r])=>segmentDistanceSquared({x,y:0,z},{x:a.x,y:0,z:a.z},{x:b.x,y:0,z:b.z})<(r+.12)**2);}
function updateEnemies(dt){for(const e of enemies){if(!e.active)continue;const a=e.actor,p=a.root.position;e.cooldown=Math.max(0,e.cooldown-dt);e.hit=Math.max(0,e.hit-dt);a.root.rotation.z=Math.sin((.18-e.hit)*30)*e.hit*.3;if(e.dead>0){e.dead-=dt;a.tick(dt,0);if(e.dead<.4)a.root.scale.setScalar(Math.max(.02,e.dead/.4));if(e.dead<=0){e.active=false;a.root.visible=false;if(e.tour)e.reappear=3;}continue;}
    const target=e.tour?e.home.clone().add(new THREE.Vector3(Math.sin(time*.22+e.id)*3,0,Math.cos(time*.22+e.id)*2)):player.position.clone(),distance=p.distanceTo(target),range=e.tour?.65:e.type.range;let moving=0;
    if((distance>range||!e.tour&&!clearSight(p,target))&&!a.locked){e.pathTime-=dt;if(e.pathTime<=0){e.path=nav.route(p,target);e.pathTime=.7+e.id*.025;}while(e.path.length&&Math.hypot(e.path[0].x-p.x,e.path[0].z-p.z)<.5)e.path.shift();const waypoint=e.path[0]||target,v=waypoint.clone().sub(p).setY(0).normalize();for(const other of enemies){if(other===e||!other.active||other.dead)continue;const d=p.clone().sub(other.actor.root.position).setY(0),len=d.length();if(len>0&&len<1.4)v.addScaledVector(d,(1.4-len)/len*1.7);}v.normalize();e.velocity.lerp(v.multiplyScalar(e.type.speed),1-Math.exp(-dt*8));const nx=p.x+e.velocity.x*dt,nz=p.z+e.velocity.z*dt,old=p.clone();if(!world.blocked(nx,p.z,.58))p.x=nx;if(!world.blocked(p.x,nz,.58))p.z=nz;moving=Math.hypot(p.x-old.x,p.z-old.z)/dt;e.targetAngle=Math.atan2(e.velocity.x,e.velocity.z);}else{e.velocity.multiplyScalar(Math.exp(-dt*12));e.targetAngle=Math.atan2(target.x-p.x,target.z-p.z);if(!e.tour&&!e.cooldown&&!a.locked&&!player.respawn&&Math.abs(p.y-player.position.y)<3){e.cooldown=e.type.attack+1.1;a.action('Punch',e.type.attack);event('enemy-windup',{id:e.id});}}
    a.root.rotation.y+=Math.atan2(Math.sin(e.targetAngle-a.root.rotation.y),Math.cos(e.targetAngle-a.root.rotation.y))*(1-Math.exp(-dt*10));p.y=world.height(p.x,p.z);a.tick(dt,moving,()=>{if(e.tour||e.dead)return;if(e.type.weapon==='rifle'){const origin=p.clone().add(new THREE.Vector3(0,1.5,0)),d=player.position.clone().add(new THREE.Vector3(0,1.4,0)).sub(origin);bolt(origin,d,{owner:'enemy',damage:e.type.damage,speed:14,color:'#ea926d'});fx.puff(origin,{count:3,color:'#f0b58a',life:.12,size:.07,speed:.3});}else if(p.distanceTo(player.position)<e.type.range+.25){playerHit(e.type.damage,p);fx.ring(p.clone().add(new THREE.Vector3(0,1.1,0)),{radius:1.1,color:'#efba86',life:.15,vertical:true});}event('enemy-contact',{id:e.id});});
    if(e.hand){e.hand.getWorldPosition(from);a.root.worldToLocal(from);e.gear.root.position.copy(from);e.gear.root.rotation.set(e.type.weapon==='rifle'?0:-.7-(a.locked?Math.sin(a.actionTime/e.type.attack*Math.PI)*1.5:0),Math.PI,0);}e.badge.material.color.set(e.hit?'#f3d49d':e.type.color);
  }for(const e of enemies)if(!e.active&&e.reappear>0&&round.phase==='tour'){e.reappear-=dt;if(e.reappear<=0){e.active=true;e.hp=e.type.hp;e.dead=0;e.actor.root.visible=true;e.actor.root.scale.setScalar(1);e.actor.root.position.copy(e.home);e.actor.reset();}}}
function updateTowers(dt){for(const t of towers){t.cooldown=Math.max(0,t.cooldown-dt);t.recoil*=Math.exp(-dt*16);if(t.kind==='beacon'){t.head.rotation.y=time*.5;if(time%3<dt){fx.ring(t.root.position.clone().add(new THREE.Vector3(0,.1,0)),{radius:4,color:'#b3e1c0',life:1});if(player.position.distanceTo(t.root.position)<5)player.health=Math.min(100,player.health+8);}continue;}const target=enemies.filter(e=>e.active&&!e.dead&&!e.tour&&e.actor.root.position.distanceTo(t.root.position)<18&&world.obstacles.every(([x,z,r])=>Math.hypot(x-t.root.position.x,z-t.root.position.z)<1||segmentDistanceSquared({x,y:0,z},{x:t.root.position.x,y:0,z:t.root.position.z},{x:e.actor.root.position.x,y:0,z:e.actor.root.position.z})>(r+.12)**2)).sort((a,b)=>a.hp-b.hp)[0];if(target){const d=target.actor.root.position.clone().sub(t.root.position),angle=Math.atan2(-d.x,-d.z);t.head.rotation.y+=Math.atan2(Math.sin(angle-t.head.rotation.y),Math.cos(angle-t.head.rotation.y))*(1-Math.exp(-dt*8));if(t.cooldown===0){t.cooldown=t.kind==='plasma'?1.3:1.7;t.recoil=.12;t.root.updateMatrixWorld(true);const origin=t.muzzles[0].getWorldPosition(new THREE.Vector3()),direction=target.actor.root.position.clone().add(new THREE.Vector3(0,1.2,0)).sub(origin);bolt(origin,direction,{owner:'tower',damage:10,speed:t.kind==='plasma'?26:20,color:t.kind==='plasma'?'#a3e4db':'#e6cf92'});fx.puff(origin,{count:6,color:'#ecdca4',size:.08,life:.2,speed:1});event('tower-fire',{tower:t.kind});}}t.head.position.y=1.4+t.recoil;}}
function updateBolts(dt){for(const b of bolts){if(b.life<=0){b.mesh.visible=false;continue;}b.life-=dt;const old=b.mesh.position.clone();b.mesh.position.addScaledVector(b.velocity,dt);let hit=false;if(b.owner==='enemy'){const p=player.position.clone().add(new THREE.Vector3(0,1.25,0));if(segmentDistanceSquared(p,old,b.mesh.position)<.62*.62){playerHit(b.damage,old);hit=true;}}else for(const e of enemies){if(!e.active||e.dead)continue;const p=e.actor.root.position.clone().add(new THREE.Vector3(0,1.2,0));if(segmentDistanceSquared(p,old,b.mesh.position)<.8*.8){enemyHit(e,b.damage,b.owner==='player'?'plasma':'tower');hit=true;break;}}const p=b.mesh.position;if(p.y<world.height(p.x,p.z)+.05||world.obstacles.some(([x,z,r])=>Math.hypot(p.x-x,p.z-z)<r&&p.y<world.height(x,z)+3)){hit=true;fx.puff(p,{count:5,color:'#c9d4ab',size:.06,life:.25,speed:.6});}if(hit){b.life=0;b.mesh.visible=false;}}for(const t of trail){t.life-=dt;t.mesh.visible=t.life>0;t.mesh.material.opacity=Math.max(0,t.life/.11)*.55;}}
function updateCamera(dt=0){const p=player.position,bob=reduced.matches||state.flight?0:Math.sin(stride*2)*.016*graphics.bob*Math.min(1,player.velocity.length());camera.position.copy(p).add(new THREE.Vector3(0,handling.eye+bob*(1-handling.ads*.9)-(reduced.matches?0:handling.land),0));camera.rotation.set(pitch,yaw,0);if(state.camera==='third'){camera.position.add(new THREE.Vector3(0,1.05,5.5).applyAxisAngle(up,yaw));camera.lookAt(p.clone().add(new THREE.Vector3(0,1.6,0)).add(new THREE.Vector3(-Math.sin(yaw)*3,0,-Math.cos(yaw)*3)));camera.position.y=Math.max(camera.position.y,world.height(camera.position.x,camera.position.z)+.6);}camera.fov=graphics.fov-(state.weapon==='rifle'?handling.ads*handling.ads*(3-2*handling.ads)*16:0)+(reduced.matches?0:handling.sprint*4);if(!reduced.matches)camera.rotation.z=Math.sin(time*65)*shake*graphics.shake*.18;camera.updateMatrixWorld(true);hero.root.visible=state.camera==='third'&&player.respawn<=0;}
function ui(){const active=round.phase==='active'||round.phase==='between';$('#round-label').textContent=active?'DEMO ROUND · WAVE '+Math.max(1,round.wave)+' / 3':round.phase==='complete'?'ROUND COMPLETE':'FREE EXPLORATION';$('#objective').textContent=active?(round.phase==='between'?'Next wave forming…':round.remaining+' sentinels remaining · Unlimited respawns'):round.phase==='complete'?'All three waves cleared. Replay or explore in flight.':'Patrolling skirmisher, ranger and guard. Try both weapons.';$('#round').textContent=active?'Restart round':round.phase==='complete'?'Replay round':'Start round';$('#mode').textContent=(state.flight?'FLIGHT · ':handling.mode.toUpperCase()+' · ')+(state.camera==='first'?'FIRST PERSON':'THIRD PERSON');$('#health').textContent=Math.ceil(player.health);$('#health-bar').style.width=player.health+'%';$('#stats').textContent=state.hits+' hits · '+round.respawns+' respawns';$('#heat-bar').style.width=heat*100+'%';$('#weapon-state').textContent=state.weapon==='sword'?(aim?'GUARDING':attackTime?'CUT '+(combo+1)+' / 3':'SABLE EDGE · READY'):vent?'VENTING · '+vent.toFixed(1)+' s':'PLASMA · '+Math.round(heat*100)+'% HEAT';$('#crosshair').style.opacity=player.respawn||!state.playing?'0':String(1-(state.weapon==='rifle'?handling.ads*.9:0));}
function step(dt){if(!ready||lost||state.paused)return;dt=Math.min(.04,Math.max(0,dt));if(!dt)return;time+=dt;player.invulnerable=Math.max(0,player.invulnerable-dt);if(player.respawn>0){player.respawn-=dt;if(player.respawn<=0){resetPlayer();event('respawn');notice('Reformed · Back in the fight',2);}}const moving=move(dt);updateCamera(dt);shotDelay=Math.max(0,shotDelay-dt);if(vent>0){vent=Math.max(0,vent-dt);heat=Math.max(0,heat-dt*1.2);}else heat=Math.max(0,heat-dt*.17);if((attackHeld||attackQueued)&&player.respawn<=0){if(state.weapon==='sword')beginSwing();else fire();}if(attackTime>0){attackTime+=dt;if(attackTime>=attackDuration)attackTime=0;}rig.update(dt,{weapon:state.weapon,attack:attackTime/attackDuration,combo,moving,aim,ads:handling.ads,sprint:handling.sprint,slide:handling.slide/.82,vent,bob:reduced.matches?0:graphics.bob,look,time});look=[0,0];if(attackTime)swordContact();const spawnCount=advanceRound(round,dt);if(spawnCount){spawn(round.remaining);notice('Wave '+round.wave+' · '+round.remaining+' sentinels');}updateEnemies(dt);updateTowers(dt);updateBolts(dt);fx.tick(dt);world.animate(time);hitMark=Math.max(0,hitMark-dt);damageMark=Math.max(0,damageMark-dt);shake=Math.max(0,shake-dt*.3);noticeTime=Math.max(0,noticeTime-dt);$('#notice').style.opacity=noticeTime>0?'1':'0';$('#hitmarker').style.opacity=Math.min(1,hitMark*8);$('#damage').style.opacity=damageMark*1.8;uiTimer+=dt;if(uiTimer>.1){uiTimer=0;ui();}}
function draw(){if(!ready||lost)return;const w=innerWidth,h=innerHeight,dpr=renderer.getPixelRatio();if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr))renderer.setSize(w,h,false);camera.aspect=handsCamera.aspect=w/h;handsCamera.fov=(w/h<.8?85:65)-(state.weapon==='rifle'?handling.ads*9:0);camera.updateProjectionMatrix();handsCamera.updateProjectionMatrix();paint.setVariant('v5',{ink:graphics.line>0,paint:graphics.texture>0,light:'golden'},w,h,scene);paint.tune(graphics);scene.fog.density=graphics.fog;sun.shadow.radius=1.6;renderer.info.reset();paint.setVariant('v5',{ink:graphics.line>0,paint:graphics.texture>0,light:'golden'},w,h,handsScene);paint.tune(graphics);fx.faceCamera(camera);renderer.autoClear=true;renderer.render(scene,camera);if(state.camera==='first'&&player.respawn<=0){renderer.autoClear=false;renderer.clearDepth();renderer.render(handsScene,handsCamera);}}
function frame(now){requestAnimationFrame(frame);const elapsed=now-last;last=now;if(!ready||lost||document.hidden)return;if(!state.paused&&!manual){timings.push(elapsed);if(timings.length>1200)timings.shift();const dt=Math.min(.1,elapsed/1000),n=Math.max(1,Math.ceil(dt/.025));for(let i=0;i<n;i++)step(dt/n);}draw();}

$('#enter').onclick=enter;$('#round').onclick=()=>{startRound();if(state.playing)notice('Click Enter to resume the round');};$('#camera').onclick=toggleCamera;$('#fly').onclick=toggleFlight;$('#reset').onclick=()=>resetArena();$('#retry').onclick=()=>location.reload();$('#graphics').onclick=()=>overlay('#settings',$('#settings').hidden);$('#close-settings').onclick=()=>overlay('#settings',false);$('#help').onclick=()=>overlay('#controls',$('#controls').hidden);$('#close-help').onclick=()=>overlay('#controls',false);
document.querySelectorAll('[data-world]').forEach(b=>b.onclick=()=>selectWorld(b.dataset.world));document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>chooseWeapon(b.dataset.weapon));document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{applyGraphics(GRAPHICS_PRESETS[b.dataset.preset].graphics);$('#preset-status').textContent=GRAPHICS_PRESETS[b.dataset.preset].name+' applied. Original 1.3.1 stays saved.';});$('#restore').onclick=()=>{applyGraphics(GRAPHICS_DEFAULTS);$('#preset-status').textContent='Painted-Anime-Inkline 1.3.2 defaults restored. Original 1.3.1 stays saved.';};$('#save-preset').onclick=()=>{const blob=new Blob([JSON.stringify({format:'worldheart-ink-preset-1',artDirection:ART_DIRECTION_VERSION,graphics},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='worldheart-ink-custom-preset.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('#load-preset').onclick=()=>$('#preset-file').click();$('#preset-file').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>20000)throw Error('Preset file is too large');const data=JSON.parse(await file.text());if(data.format!=='worldheart-ink-preset-1'||!['1.3.1',ART_DIRECTION_VERSION].includes(data.artDirection)||!data.graphics||Object.values(data.graphics).some(v=>typeof v!=='number'||!Number.isFinite(v)))throw Error('Choose a Worldheart 1.3.1 or 1.3.2 graphics preset');applyGraphics(data.graphics);$('#preset-status').textContent='Custom preset loaded.';}catch(error){$('#preset-status').textContent=error.message;}e.target.value='';};
window.addEventListener('keydown',e=>{if(!ready||e.target.closest('input,select'))return;if(e.code==='Escape'){overlay('#settings',false);$('#controls').hidden=true;pause(true);document.exitPointerLock?.();return;}if(e.code==='KeyG'&&!e.repeat){overlay('#settings',$('#settings').hidden);return;}if(state.paused)return;const codes=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','ShiftRight','ControlLeft','ControlRight','KeyC','Space','KeyJ','Digit1','Digit2','KeyF','KeyV','KeyR'];if(!codes.includes(e.code))return;e.preventDefault();keys.add(e.code);if(e.code==='KeyJ'&&!e.repeat)pressAttack();if(!e.repeat){if(e.code==='Space')leap();if(e.code==='Digit1')chooseWeapon('sword');if(e.code==='Digit2')chooseWeapon('rifle');if(e.code==='KeyF')toggleFlight();if(e.code==='KeyV')toggleCamera();if(e.code==='KeyR')startVent();}});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='KeyJ')attackHeld=false;});window.addEventListener('blur',()=>{clearInput();if(state.playing){pause(true);$('#entry').hidden=false;}});document.addEventListener('visibilitychange',()=>{clearInput();last=performance.now();if(document.hidden&&state.playing){pause(true);$('#entry').hidden=false;}});
document.addEventListener('pointerlockchange',()=>{if(document.pointerLockElement!==canvas&&state.playing&&$('#settings').hidden&&$('#controls').hidden){pause(true);$('#entry-title').textContent='Take a breath.';$('#enter').textContent='Resume exploring';$('#entry').hidden=false;}});document.addEventListener('pointerlockerror',()=>notice('Click to attack. Drag to look. J holds an attack.',5));canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(state.paused)return;canvas.focus();if(document.pointerLockElement!==canvas){drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,button:e.button};canvas.setPointerCapture(e.pointerId);if(e.button===2)aim=true;}});window.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId&&drag.button===0&&!drag.moved&&!state.paused)pressAttack();if(e.button===0)attackHeld=false;if(e.button===2)aim=false;drag=null;});canvas.addEventListener('pointercancel',clearInput);document.addEventListener('mousemove',e=>{if(state.paused||document.pointerLockElement!==canvas)return;const dx=THREE.MathUtils.clamp(e.movementX,-150,150),dy=THREE.MathUtils.clamp(e.movementY,-150,150);yaw-=dx*.0022*graphics.sensitivity*(1-handling.ads*.32);pitch=THREE.MathUtils.clamp(pitch-dy*.0022*graphics.sensitivity*(1-handling.ads*.32),-1.45,1.45);look=[dx,dy];updateCamera();});canvas.addEventListener('pointermove',e=>{if(state.paused||drag?.id!==e.pointerId||document.pointerLockElement===canvas)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||= Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5;if(!drag.moved)return;yaw-=dx*.005*graphics.sensitivity*(1-handling.ads*.32);pitch=THREE.MathUtils.clamp(pitch-dy*.004*graphics.sensitivity*(1-handling.ads*.32),-1.45,1.45);look=[dx,dy];drag.x=e.clientX;drag.y=e.clientY;updateCamera();});
const pad=$('#stick');function padMove(e){if(e.pointerId!==stickPointer)return;const r=pad.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,d=Math.max(38,Math.hypot(x,y));stick.x=x/d;stick.y=y/d;$('#thumb').style.transform=`translate(${stick.x*32}px,${stick.y*32}px)`;}pad.onpointerdown=e=>{e.preventDefault();stickPointer=e.pointerId;pad.setPointerCapture(e.pointerId);padMove(e);};pad.onpointermove=padMove;for(const name of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(name,()=>{stickPointer=null;stick.x=stick.y=0;$('#thumb').style.transform='';});$('#touch-run').onclick=()=>{touchRun=!touchRun;$('#touch-run').setAttribute('aria-pressed',String(touchRun));};for(const [id,code] of [['touch-jump','Space'],['touch-down','KeyC']]){const b=$('#'+id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(code);if(code==='Space')leap();};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>keys.delete(code));}$('#touch-aim').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);aim=true;};for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#touch-aim').addEventListener(name,()=>aim=false);$('#touch-attack').onpointerdown=e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pressAttack();};for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#touch-attack').addEventListener(name,()=>attackHeld=false);

async function boot(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.VSMShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.info.autoReset=false;applyGraphics(GRAPHICS_PRESETS[new URLSearchParams(location.search).get('preset')]?.graphics||graphics);paint=await createSurfaceMaterials();worlds=createWorlds(paint);worlds.forEach(w=>scene.add(w.root));fx=createEffects(scene);k=kit(paint);rig=createWeapons(paint);handsScene.add(rig.root);hero=await createVeyActor(paint);scene.add(hero.root);heroGear={sword:k.weapon('sword'),rifle:k.weapon('rifle')};for(const g of Object.values(heroGear)){g.root.scale.setScalar(.8);hero.root.add(g.root);}const types=Object.keys(UNIT_TYPES);for(let i=0;i<9;i++){const type=UNIT_TYPES[types[i%3]],unit=await createDemoUnit(paint,type,i%3);scene.add(unit.actor.root);enemies.push({id:i,...unit,velocity:new THREE.Vector3(),active:false,reappear:0});$('#load-status').textContent='Preparing articulated sentinel '+(i+1)+' / 9…';}for(const kind of ['cannon','plasma','beacon']){const t=k.tower(kind);towers.push(t);scene.add(t.root);}const geometry=new THREE.CapsuleGeometry(.055,.45,2,6);for(let i=0;i<80;i++){const mesh=plasmaMesh();mesh.visible=false;scene.add(mesh);bolts.push({mesh,velocity:new THREE.Vector3(),life:0});}for(let i=0;i<14;i++){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,4),new THREE.MeshBasicMaterial({color:'#f0d4a0',transparent:true,opacity:.4,depthWrite:false}));mesh.visible=false;scene.add(mesh);trail.push({mesh,life:0});}
    $('#camera').textContent=state.camera==='third'?'V · First person':'V · Third person';ready=true;selectWorld(new URLSearchParams(location.search).get('world')||'meadow');rig.update(0);updateCamera();ui();$('#loading').hidden=true;window.INK_ARENA={hero,artDirection:ART_DIRECTION_VERSION,state,player,handling,round,enemies,towers,rig,graphics,events,defaults:GRAPHICS_DEFAULTS,step,render:draw,selectWorld,startRound,reset:resetArena,chooseWeapon,applyGraphics,hitEnemy:enemyHit,hitPlayer:playerHit,pause,isBlocked:(x,z,r=.7)=>world.blocked(x,z,r),get ready(){return ready;},get time(){return time;},get foliage(){return worlds[0].foliage;},get attack(){return {phase:attackTime/attackDuration,combo,queued:attackQueued};},get camera(){return {yaw,pitch,position:camera.position.toArray(),fov:camera.fov};},setView(y,p=0){yaw=y;pitch=p;updateCamera();},get manual(){return manual;},set manual(value){manual=value;},get timings(){return timings.slice();},get metrics(){return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,bolts:bolts.filter(b=>b.life>0).length,effects:fx.active,enemies:enemies.filter(e=>e.active&&!e.dead).length};}};draw();last=performance.now();requestAnimationFrame(frame);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;pause(true);$('#loading').hidden=false;$('#load-status').textContent='Graphics interrupted. Waiting for recovery…';});canvas.addEventListener('webglcontextrestored',()=>{lost=false;$('#loading').hidden=true;$('#entry').hidden=false;last=performance.now();});
  }catch(error){window.INK_ARENA_ERROR=String(error);$('#load-status').textContent=error.message;$('#retry').hidden=false;console.error(error);}}
boot();
$('#audio').onclick=()=>{state.muted=!state.muted;$('#audio').textContent=state.muted?'Enable sound effects':'Mute sound effects';$('#audio').setAttribute('aria-pressed',String(state.muted));};

// Pointer events only report the first pressed and last released mouse button.
// Mouse events report each button, so ADS and trigger chords remain independent.
canvas.addEventListener('mousedown',e=>{if(state.paused||document.pointerLockElement!==canvas)return;if(e.button===0)pressAttack();if(e.button===2)aim=true;});
window.addEventListener('mouseup',e=>{if(e.button===0)attackHeld=false;if(e.button===2)aim=false;});
