import {resolve} from 'node:path';
import {writeFileSync} from 'node:fs';

// Assisted aiming reads unit positions. Damage, movement, firing, cooling,
// deaths and wave advancement use the same real-time input path as play.
export async function run({browser,base,out,check,errors}){
  const context=await browser.newContext({viewport:{width:1280,height:800},recordVideo:{dir:out,size:{width:1280,height:800}}}),page=await context.newPage();
  page.on('pageerror',e=>errors.push(String(e)));await page.goto(base+'/atmospheric-arena.html?world=canyon');await page.waitForFunction(()=>window.INK_ARENA?.ready,null,{timeout:60000});await page.locator('#round').click();await page.locator('#enter').click();await page.keyboard.press('Digit2');
  let mx=640,my=400,oldWave=0;const began=Date.now(),samples=[];await page.mouse.move(mx,my);await page.keyboard.down('KeyJ');
  while(Date.now()-began<100000){const s=await page.evaluate(()=>{const a=INK_ARENA,p=a.player.position,c=a.camera;const targets=a.enemies.filter(e=>e.active&&!e.dead).sort((x,y)=>x.actor.root.position.distanceTo(p)-y.actor.root.position.distanceTo(p));const e=targets[0];return {round:{...a.round},health:a.player.health,paused:a.state.paused,view:c,target:e?{position:e.actor.root.position.toArray(),distance:e.actor.root.position.distanceTo(p)}:null,pos:p.toArray(),shots:a.state.shots,hits:a.state.hits};});samples.push(s);if(s.round.wave!==oldWave){oldWave=s.round.wave;console.log('Live input wave '+oldWave+' / health '+s.health);await page.screenshot({path:resolve(out,'live-wave-'+oldWave+'.png')});}if(s.round.phase==='complete')break;
    if(s.target){const [x,y,z]=s.target.position,dx=x-s.view.position[0],dy=y+1.2-s.view.position[1],dz=z-s.view.position[2],wantYaw=Math.atan2(-dx,-dz),wantPitch=Math.atan2(dy,Math.hypot(dx,dz)),yaw=Math.atan2(Math.sin(wantYaw-s.view.yaw),Math.cos(wantYaw-s.view.yaw)),pitch=wantPitch-s.view.pitch;mx+=Math.max(-120,Math.min(120,-yaw/.0022));my+=Math.max(-120,Math.min(120,-pitch/.0022));await page.mouse.move(mx,my);if(s.target.distance>9){await page.keyboard.down('KeyW');await page.keyboard.up('KeyS');}else{await page.keyboard.up('KeyW');if(s.target.distance<3.5)await page.keyboard.down('KeyS');else await page.keyboard.up('KeyS');}}else{await page.keyboard.up('KeyW');await page.keyboard.up('KeyS');}await page.waitForTimeout(100);
  }
  await page.keyboard.up('KeyJ');await page.keyboard.up('KeyW');await page.keyboard.up('KeyS');const result=await page.evaluate(()=>({round:{...INK_ARENA.round},state:{...INK_ARENA.state},events:INK_ARENA.events,metrics:INK_ARENA.metrics}));check('Real-time assisted-input combat completes all three waves',result.round.phase==='complete'&&result.round.kills===15&&result.state.shots>20&&result.events.some(e=>e.kind==='kill'&&e.source==='plasma'),{round:result.round,state:result.state});await page.screenshot({path:resolve(out,'live-final.png')});writeFileSync(resolve(out,'live-input.json'),JSON.stringify({kind:'Real-time input with position-assisted aiming, no damage or wave overrides',elapsedMs:Date.now()-began,result,samples},null,2));const video=page.video();await context.close();await video.saveAs(resolve(out,'live-combat.webm'));check('Live input run has no browser errors',errors.length===0,errors);
}
