import {resolve} from 'node:path';
import {writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';

export async function run({page,browser,base,out,check,shot,settle,difference,sharp,errors,requests}){
  const ready=async p=>p.waitForFunction(()=>window.INK_ARENA?.ready||window.INK_ARENA_ERROR,null,{timeout:60000});
  const value=(fn,arg)=>page.evaluate(fn,arg),tick=async seconds=>value(seconds=>{const a=INK_ARENA;for(let i=0;i<Math.ceil(seconds*120);i++)a.step(1/120);a.render();},seconds);
  await page.goto(base+'/atmospheric-arena.html');await ready(page);check('Arena boots with pinned rig and three loadouts',await value(()=>INK_ARENA.enemies.length===9&&new Set(INK_ARENA.enemies.map(e=>e.type.id)).size===3));
  const initial=await value(()=>({storage:JSON.stringify(localStorage),defaults:{...INK_ARENA.graphics}}));
  const contrast=await value(()=>{const rgb=s=>(s.match(/[\d.]+/g)||[]).map(Number),lum=c=>{const v=c.slice(0,3).map(n=>(n/=255)<=.04045?n/12.92:((n+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722;},bg=e=>{const c=rgb(getComputedStyle(e).backgroundColor);if((c[3]??1)>=.99)return c;const b=e.parentElement?bg(e.parentElement):[16,28,43];return c.slice(0,3).map((v,i)=>v*(c[3]??1)+b[i]*(1-(c[3]??1)));};return [...document.querySelectorAll('header a,header button,header span,.veil h2,.veil p,.veil small,.veil a,.weapon-panel button,.weapon-panel small,.player-panel small')].filter(e=>e.offsetParent).map(e=>{const s=getComputedStyle(e),a=lum(rgb(s.color)),b=lum(bg(e));return {text:e.textContent.trim().slice(0,35),ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),required:parseFloat(s.fontSize)>=24?3:4.5};});});check('Arena interface text meets AA contrast',contrast.every(c=>c.ratio>=c.required),contrast);
  check('Initial graphics match owner-selected Vivid Paint',initial.defaults.line===2.8&&initial.defaults.fog===.0225&&initial.defaults.saturation===1.3&&initial.defaults.shadowDepth===.35,initial.defaults);
  const manifest=JSON.parse(readFileSync('art-candidates/atmospheric-ink-v1.3.1.json','utf8')),archive=await page.request.get(base+'/art-candidates/atmospheric-ink-v1.3.1.zip');
  const digest=createHash('sha256').update(await archive.body()).digest('hex');check('Download serves exact locked archive',archive.ok()&&digest===manifest.archiveSha256,{digest,expected:manifest.archiveSha256});
  await page.locator('#enter').click();await page.waitForTimeout(500);check('Enter captures pointer and starts live simulation',await value(()=>document.pointerLockElement===document.querySelector('#world')&&!INK_ARENA.state.paused&&INK_ARENA.time>0));
  const start=await value(()=>INK_ARENA.player.position.toArray());await page.keyboard.down('KeyW');await page.waitForTimeout(1100);await page.keyboard.up('KeyW');const walk=await value(()=>({pos:INK_ARENA.player.position.toArray(),clips:INK_ARENA.enemies.filter(e=>e.active).map(e=>e.actor.current)}));check('Real WASD moves player with visible walking patrols',walk.pos[2]<start[2]-1.5&&walk.clips.includes('Walking'),walk);
  const camera=await value(()=>INK_ARENA.camera);await page.mouse.move(930,520);await page.mouse.move(1000,535,{steps:5});check('Pointer-locked mouse changes view immediately',await value(c=>INK_ARENA.camera.yaw!==c.yaw,camera));
  await page.keyboard.press('Space');await page.waitForTimeout(230);check('Jump has upward motion',await value(()=>INK_ARENA.player.jump>.4));await page.waitForTimeout(750);check('Jump settles on terrain',await value(()=>INK_ARENA.player.jump===0));
  await page.keyboard.press('KeyF');const altitude=await value(()=>INK_ARENA.player.position.y);await page.keyboard.down('Space');await page.waitForTimeout(500);await page.keyboard.up('Space');check('Flight ascends with Space',await value(y=>INK_ARENA.state.flight&&INK_ARENA.player.position.y>y+1,altitude));await page.keyboard.down('KeyC');await page.waitForTimeout(350);await page.keyboard.up('KeyC');await page.keyboard.press('KeyF');check('Landing restores grounded controller',await value(()=>!INK_ARENA.state.flight&&INK_ARENA.player.vertical===0));
  await value(()=>{INK_ARENA.manual=true;INK_ARENA.reset();INK_ARENA.pause(false);INK_ARENA.setView(0,-.05);const e=INK_ARENA.enemies[0];e.actor.root.position.set(0,INK_ARENA.player.position.y,9.05);e.home.copy(e.actor.root.position);e.tour=true;e.type={...e.type,speed:0};for(const other of INK_ARENA.enemies.slice(1))other.active=other.actor.root.visible=false;});
  await page.keyboard.press('KeyJ');await tick(.10);check('Sword anticipation cannot damage a target',await value(()=>INK_ARENA.state.hits===0));
  const images=[],motion=[];
  for(let i=0;i<36;i++){await tick(1/60);motion.push(await value(()=>INK_ARENA.rig.joints));if(i%5===0){const file='sword-phase-'+String(i).padStart(2,'0')+'.png';await page.screenshot({path:resolve(out,file)});images.push(file);}}
  const swordResult=await value(()=>({hits:INK_ARENA.state.hits,events:INK_ARENA.events.filter(e=>['sword-start','hit'].includes(e.kind))}));check('One sword swing hits once through its active blade path',swordResult.hits===1,swordResult);
  let maxStep=0,finite=true,maxLengthError=0;for(let n=0;n<motion.length;n++)for(let side=0;side<2;side++){const [s,e,h]=motion[n].slice(side*3,side*3+3);finite&&=[...s,...e,...h].every(Number.isFinite);const dist=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));maxLengthError=Math.max(maxLengthError,Math.abs(dist(s,e)-.45),Math.abs(dist(e,h)-.44));if(n)for(let j=0;j<3;j++)maxStep=Math.max(maxStep,dist(motion[n][side*3+j],motion[n-1][side*3+j]));}
  check('Articulated arms remain finite with fixed limb lengths through cut',finite&&maxLengthError<.001&&maxStep<.30,{maxStep,maxLengthError});
  const thumbs=await Promise.all(images.map(async file=>sharp(resolve(out,file)).resize(400,250).toBuffer()));await sharp({create:{width:1600,height:500,channels:3,background:'#132533'}}).composite(thumbs.map((input,i)=>({input,left:(i%4)*400,top:Math.floor(i/4)*250}))).png().toFile(resolve(out,'sword-sequence.png'));
  await value(()=>{const e=INK_ARENA.enemies[0];e.actor.root.position.z=-8;e.home.copy(e.actor.root.position);});const hits=await value(()=>INK_ARENA.state.hits);await page.keyboard.press('KeyJ');await tick(.9);check('Out-of-range sword swing misses',await value(n=>INK_ARENA.state.hits===n,hits));
  await page.keyboard.press('Digit2');await value(()=>{INK_ARENA.setView(0,-.055);const e=INK_ARENA.enemies[0];e.hp=300;e.actor.root.position.set(0,INK_ARENA.player.position.y,4);e.home.copy(e.actor.root.position);});await page.keyboard.down('KeyJ');await tick(.6);await page.keyboard.up('KeyJ');await tick(.2);const rifle=await value(()=>({shots:INK_ARENA.state.shots,hits:INK_ARENA.events.filter(e=>e.kind==='hit'&&e.source==='plasma').length,joints:INK_ARENA.rig.joints}));check('Held plasma fires repeatedly and swept bolts hit at range',rifle.shots>=3&&rifle.hits>=2,rifle);await shot('plasma');
  await page.keyboard.press('KeyR');await tick(.2);check('R visibly vents a warm rifle',await page.locator('#weapon-state').textContent().then(t=>t.startsWith('VENTING')));await tick(1.1);check('Vent returns the weapon to ready',await page.locator('#weapon-state').textContent().then(t=>t.includes('0% HEAT')));
  await value(()=>{INK_ARENA.startRound();INK_ARENA.pause(false);});await tick(.6);check('Round starts with all three first-wave enemies',await value(()=>INK_ARENA.round.wave===1&&INK_ARENA.round.remaining===3&&INK_ARENA.metrics.enemies===3));
  const enemyBefore=await value(()=>INK_ARENA.enemies[0].actor.root.position.toArray());await tick(3);check('Hostile units navigate toward the player',await value(p=>INK_ARENA.enemies[0].actor.root.position.distanceTo({x:p[0],y:p[1],z:p[2]})>.5,enemyBefore));
  await tick(16);check('Hostile and tower attacks produce timed contacts and projectiles',await value(()=>INK_ARENA.events.some(e=>e.kind==='enemy-contact')&&INK_ARENA.events.some(e=>e.kind==='tower-fire')),await value(()=>INK_ARENA.events.slice(-25)));
  await value(()=>{INK_ARENA.player.invulnerable=0;INK_ARENA.hitPlayer(200,INK_ARENA.player.position.clone().addScalar(1));});check('Lethal damage starts free respawn',await value(()=>INK_ARENA.player.respawn>0&&INK_ARENA.round.respawns===1));await tick(1.1);check('Respawn restores health and keeps the same round',await value(()=>INK_ARENA.player.health===100&&INK_ARENA.player.invulnerable>0&&INK_ARENA.round.wave===1));
  for(let wave=1;wave<=3;wave++){await value(()=>{for(const e of INK_ARENA.enemies)if(e.active&&!e.dead)INK_ARENA.hitEnemy(e,1000,'probe');});await tick(2.7);}
  check('Controlled lifecycle clears all 15 enemies and all three waves',await value(()=>INK_ARENA.round.phase==='complete'&&INK_ARENA.round.kills===15),await value(()=>INK_ARENA.round));await value(()=>INK_ARENA.startRound());await tick(.6);check('Completed round can restart cleanly',await value(()=>INK_ARENA.round.wave===1&&INK_ARENA.round.kills===0&&INK_ARENA.round.respawns===0));
  await value(()=>{INK_ARENA.reset();INK_ARENA.pause(true);document.exitPointerLock();document.querySelector('#entry').hidden=true;});
  for(const id of ['canyon','ruins','meadow']){await page.locator('[data-world="'+id+'"]').click();await value(()=>{document.querySelector('#entry').hidden=true;INK_ARENA.setView(.22,-.08);INK_ARENA.render();});await shot(id);check(id+' renders and resets patrol state',await value(id=>INK_ARENA.state.world===id&&INK_ARENA.round.phase==='tour'&&INK_ARENA.metrics.enemies===3,id));}
  const placements=await value(()=>{const a=INK_ARENA,result=[];for(const world of ['meadow','canyon','ruins']){a.selectWorld(world);a.startRound();a.pause(false);for(let wave=1;wave<=3;wave++){for(let n=0;n<330;n++)a.step(1/120);result.push({world,wave,blocked:a.enemies.filter(e=>e.active&&!e.dead&&a.isBlocked(e.actor.root.position.x,e.actor.root.position.z,.58)).map(e=>e.id)});for(const e of a.enemies)if(e.active&&!e.dead)a.hitEnemy(e,1000,'probe');}}a.selectWorld('meadow');a.pause(true);return result;});check('Every wave in all three environments spawns outside obstacles',placements.every(p=>p.blocked.length===0),placements);await page.locator('#graphics').click();await page.locator('#g-line').fill('0');await page.locator('#g-line').dispatchEvent('input');await value(()=>INK_ARENA.render());const plain=await shot('outline-off');await page.locator('#g-line').fill('4');await page.locator('#g-line').dispatchEvent('input');await value(()=>INK_ARENA.render());const thick=await shot('outline-thick');check('Contour slider changes actual rendered silhouettes',await difference(plain,thick)>.15);
  for(const [key,val] of Object.entries({fog:.025,shadowDepth:.25,saturation:1.5,texture:.2,exposure:.8,resolution:.8,fov:95,bob:0,shake:0,sensitivity:1.4})){await page.locator('#g-'+key).fill(String(val));await page.locator('#g-'+key).dispatchEvent('input');}
  const downloadEvent=page.waitForEvent('download');await page.locator('#save-preset').click();const download=await downloadEvent;await download.saveAs(resolve(out,'custom-preset.json'));await page.locator('#restore').click();check('Reset restores every Vivid default without mutating original',await value(()=>JSON.stringify(INK_ARENA.graphics)===JSON.stringify(INK_ARENA.defaults)));
  await page.locator('#preset-file').setInputFiles(resolve(out,'custom-preset.json'));await page.waitForTimeout(100);check('Saved custom graphics preset reloads',await value(()=>INK_ARENA.graphics.line===4&&INK_ARENA.graphics.saturation===1.5));await page.locator('#restore').click();await shot('graphics-panel');await page.locator('#close-settings').click();
  const raster=async()=>Buffer.from(await value(()=>{INK_ARENA.render();return document.querySelector('#world').toDataURL().split(',')[1];}),'base64'),baseline=await raster();
  for(const [key,setting] of Object.entries({texture:0,saturation:.6,shadowDepth:.05,fog:.03,exposure:.7,fov:100})){await value(([key,v])=>INK_ARENA.applyGraphics({...INK_ARENA.defaults,[key]:v}),[key,setting]);const delta=await difference(baseline,await raster());check(key+' changes rendered world pixels',delta>.15,{delta});}await value(()=>INK_ARENA.applyGraphics(INK_ARENA.defaults));
  const allocation=await value(()=>{for(const id of ['canyon','ruins','meadow']){INK_ARENA.selectWorld(id);INK_ARENA.render();}return INK_ARENA.metrics;});for(let n=0;n<3;n++)await value(()=>{for(const id of ['canyon','ruins','meadow']){INK_ARENA.selectWorld(id);INK_ARENA.render();}});check('Repeated environment changes keep GPU allocation stable',await value(m=>INK_ARENA.metrics.geometries===m.geometries&&INK_ARENA.metrics.textures===m.textures,allocation),allocation);
  await page.locator('#enter').click();await page.keyboard.down('KeyW');await tick(.3);await page.keyboard.press('Escape');const pos=await value(()=>INK_ARENA.player.position.toArray());await tick(.5);check('Escape releases pointer, pauses and clears held movement',await value(p=>!document.pointerLockElement&&INK_ARENA.state.paused&&JSON.stringify(INK_ARENA.player.position.toArray())===JSON.stringify(p),pos));await page.keyboard.up('KeyW');
  for(const width of [390,768,1600]){await page.setViewportSize({width,height:width===390?844:1000});await value(()=>{document.querySelector('#entry').hidden=true;INK_ARENA.render();});check('Responsive HUD '+width,await value(w=>document.documentElement.scrollWidth<=w,width));await page.screenshot({path:resolve(out,'layout-'+width+'.png')});}
  const pigment=await value(async()=>{
    const THREE=await import('three'),{createSurfaceMaterials}=await import('./js/arena-materials.js'),{createCandidateMaterials}=await import('./js/hard-cel-materials.js'),result={};
    for(const [id,factory] of [['surface',createSurfaceMaterials],['worldControl',createCandidateMaterials]]){const paint=await factory(),s=new THREE.Scene(),c=new THREE.PerspectiveCamera(45,1,.1,50),r=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});r.setSize(320,320);s.background=new THREE.Color('#718082');s.add(new THREE.HemisphereLight('#ffffff','#333333',2));const m=new THREE.Mesh(new THREE.BoxGeometry(2,2,2),paint.material('#ac8069'));s.add(m);c.position.set(0,0,5);c.lookAt(0,0,0);paint.setVariant('v5',{ink:true,paint:true,light:'golden'},320,320,s);r.render(s,c);const a=r.domElement.toDataURL();m.position.set(4.3,1.2,0);c.position.add(m.position);r.render(s,c);result[id]=[a,r.domElement.toDataURL()];r.dispose();}
    return result;
  });
  const delta={};for(const [id,frames] of Object.entries(pigment)){delta[id]=await difference(...frames.map(s=>Buffer.from(s.split(',')[1],'base64')));}check('Mesh translation preserves pigment; world-projected control visibly swims',delta.surface<.05&&delta.worldControl>.3,delta);writeFileSync(resolve(out,'pigment-stability.json'),JSON.stringify(delta,null,2));
  await value(()=>{INK_ARENA.manual=false;INK_ARENA.startRound();INK_ARENA.pause(false);document.querySelector('#entry').hidden=true;});await page.waitForTimeout(7000);const perf=await value(()=>{const a=INK_ARENA.timings.slice(-300).sort((x,y)=>x-y);return {samples:a.length,median:a[Math.floor(a.length*.5)],p95:a[Math.floor(a.length*.95)],metrics:INK_ARENA.metrics};});check('Native desktop combat renders sustained frames',perf.samples>120&&perf.p95<40,perf);writeFileSync(resolve(out,'performance.json'),JSON.stringify(perf,null,2));
  check('Standalone arena leaves campaign saves untouched',await value(s=>JSON.stringify(localStorage)===s,initial.storage));check('No campaign modules imported',!requests.some(u=>/\/js\/(main|modes\/ninetynine|run\/)/.test(u)));
  await value(()=>{const gl=document.querySelector('#world').getContext('webgl2');window.arenaRecovery=gl.getExtension('WEBGL_lose_context');arenaRecovery.loseContext();});await page.waitForTimeout(150);check('Graphics interruption pauses and shows recovery guidance',await page.locator('#loading').isVisible()&&await value(()=>INK_ARENA.state.paused));await value(()=>arenaRecovery.restoreContext());await page.waitForTimeout(500);check('Graphics restoration resumes rendering with entry control',await page.locator('#loading').isHidden()&&await page.locator('#enter').isVisible());
  const broken=await browser.newPage();await broken.route('**/lib/playground/RobotExpressive.glb',r=>r.abort());await broken.goto(base+'/atmospheric-arena.html');await broken.waitForFunction(()=>window.INK_ARENA_ERROR);check('Missing model offers a readable retry instead of a blank canvas',await broken.locator('#retry').isVisible()&&await broken.locator('#load-status').textContent().then(Boolean));await broken.close();
  const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}),mobile=await touch.newPage();mobile.on('pageerror',e=>errors.push(String(e)));await mobile.goto(base+'/atmospheric-arena.html');await ready(mobile);await mobile.locator('#enter').tap();const before=await mobile.evaluate(()=>INK_ARENA.camera.yaw),cdp=await touch.newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:185,y:400}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:250,y:410}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('Real touch swipe turns camera',await mobile.evaluate(b=>INK_ARENA.camera.yaw!==b,before));await mobile.locator('#touch-attack').tap();await mobile.waitForTimeout(100);check('Touch attack starts sword action',await mobile.evaluate(()=>INK_ARENA.state.swings===1));await mobile.screenshot({path:resolve(out,'touch.png')});await touch.close();
  check('No browser or shader errors',errors.length===0,errors);
}
