import {resolve} from 'node:path';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';

export async function run({page,browser,base,out,check,shot,settle,difference,sharp,errors,requests}){
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.goto(base+'/hard-cel-lab.html');await page.waitForFunction(()=>window.CANDIDATE_LAB?.ready,null,{timeout:60000});
  const initial=await page.evaluate(()=>({storage:JSON.stringify(localStorage),metrics:CANDIDATE_LAB.metrics,assets:CANDIDATE_LAB.assets,backend:(()=>{const gl=document.querySelector('canvas').getContext('webgl2'),ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),userAgent:navigator.userAgent,dpr:devicePixelRatio};})()}));
  check('Pinned scene boots with three textured models and one context',initial.metrics.models===3&&initial.metrics.contexts===1&&initial.assets.every(a=>a.textures===1),initial);
  check('Model and pigment requests use the archived assets',requests.filter(u=>/\.(gltf|png)(\?|$)/.test(u)).every(u=>u.includes('/art-candidates/hard-cel-v1/')),requests.filter(u=>/\.(gltf|png)(\?|$)/.test(u)));
  const candidate=JSON.parse(readFileSync('art-candidates/hard-cel-v1/candidate.json','utf8'));
  const contrast=await page.evaluate(()=>{
    const rgb=s=>(s.match(/[\d.]+/g)||[]).map(Number),lum=c=>{const a=c.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return a[0]*.2126+a[1]*.7152+a[2]*.0722;};
    const bg=e=>{const c=rgb(getComputedStyle(e).backgroundColor);if((c[3]??1)>=.99)return c;const under=e.parentElement?bg(e.parentElement):[255,255,255];return c.slice(0,3).map((v,i)=>v*(c[3]??1)+under[i]*(1-(c[3]??1)));};
    return [...document.querySelectorAll('p,h1,h2,h3,button,a,label,select,small,.saved,.scene-tag,.scene-note,.underbar')].filter(e=>e.offsetParent).map(e=>{const s=getComputedStyle(e),a=lum(rgb(s.color)),b=lum(bg(e)),size=parseFloat(s.fontSize);return {text:e.textContent.trim().slice(0,40),ratio:(Math.max(a,b)+.05)/(Math.min(a,b)+.05),required:size>=24||(size>=18.66&&parseInt(s.fontWeight)>=700)?3:4.5};});
  });check('Candidate interface text meets AA contrast',contrast.every(c=>c.ratio>=c.required),contrast);
  for(const file of candidate.files){const r=await page.request.get(base+'/art-candidates/hard-cel-v1/'+file.path);check('Archived identity: '+file.path,r.ok()&&createHash('sha256').update(await r.body()).digest('hex')===file.sha256);}
  const pixelView=async(p,pane)=>{const box=await p.locator('.viewport:visible').nth(pane).boundingBox(),stage=await p.locator('#stage').boundingBox();const buffer=Buffer.from((await p.locator('canvas').evaluate(c=>c.toDataURL())).split(',')[1],'base64');const meta=await sharp(buffer).metadata(),scale=meta.width/stage.width;return sharp(buffer).extract({left:Math.round((box.x-stage.x+3)*scale),top:Math.round((box.y-stage.y+2)*scale),width:Math.round((box.width-6)*scale),height:Math.round((box.height-4)*scale)}).png().toBuffer();};
  await page.locator('[data-view="commander"]').click();const baseline=await pixelView(page,0);await shot('pair-commander');
  const archived=await browser.newPage({viewport:{width:1600,height:1100},reducedMotion:'reduce'});archived.on('pageerror',e=>errors.push(String(e)));await archived.goto(base+'/art-candidates/hard-cel-v1/painted-lab.html?view=commander&compare=1');await archived.waitForFunction(()=>window.PAINTED_LAB?.ready,null,{timeout:60000});const old=await pixelView(archived,1);await archived.reload();await archived.waitForFunction(()=>window.PAINTED_LAB?.ready,null,{timeout:60000});const oldAgain=await pixelView(archived,1),control=await difference(old,oldAgain),equivalence=await difference(old,baseline);check('Original-to-original rendered control is stable',control<.02,{meanRGBDifference:control});check('Saved baseline matches archived Hard Cel rendering',equivalence<=control+.02,{meanRGBDifference:equivalence,tolerance:control+.02});await archived.close();
  const samples=[];
  for(const version of ['v2','v3','v4']){await page.locator(`button[data-version="${version}"]`).click();await settle();const variant=await pixelView(page,1);samples.push(variant);const delta=await difference(baseline,variant);check(version+' visibly differs from the original',delta>1,{meanRGBDifference:delta});await shot(version+'-commander');}
  check('All three iterations produce distinct scene pixels',(await difference(samples[0],samples[1]))>1&&(await difference(samples[0],samples[2]))>1&&(await difference(samples[1],samples[2]))>1);
  await page.locator('#layout').selectOption('all');check('Four-version grid has original plus three experiments',await page.locator('.viewport:visible').count()===4);for(const view of ['valley','commander','tower','enemy']){await page.locator(`[data-view="${view}"]`).click();await shot('all-'+view);check('All versions render '+view,await page.evaluate(()=>CANDIDATE_LAB.metrics.triangles>1000000&&CANDIDATE_LAB.camera.target.every(Number.isFinite)));}
  await page.locator('button[data-version="v1"]').click();await page.locator('#layout').selectOption('single');check('Original can be inspected full width',await page.locator('.viewport:visible').count()===1&&await page.locator('.viewport:visible').getAttribute('data-version')==='v1');
  await page.locator('button[data-version="v3"]').click();await page.locator('[data-view="commander"]').click();const textured=await shot('etched-detail');await page.locator('#paint').uncheck();const plain=await shot('etched-no-texture');check('Texture toggle affects pigment and hatching',await difference(textured,plain)>.2);await page.locator('#ink').uncheck();const bare=await shot('etched-no-contour');check('Contour toggle changes the actual image',await difference(plain,bare)>.05);await page.locator('#paint').check();await page.locator('#ink').check();
  const prior=await page.evaluate(()=>CANDIDATE_LAB.camera),rect=await page.locator('.viewport:visible').boundingBox();await page.mouse.move(rect.x+rect.width*.5,rect.y+rect.height*.5);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.5+85,rect.y+rect.height*.5+25,{steps:8});await page.mouse.up();check('Real pointer orbit changes yaw and pitch',await page.evaluate(p=>CANDIDATE_LAB.camera.yaw!==p.yaw&&CANDIDATE_LAB.camera.pitch!==p.pitch,prior));const zoom=await page.evaluate(()=>CANDIDATE_LAB.camera.distance);await page.mouse.wheel(0,-120);await settle();check('Wheel zoom works',await page.evaluate(d=>CANDIDATE_LAB.camera.distance<d,zoom));await page.locator('.viewport:visible').focus();const yaw=await page.evaluate(()=>CANDIDATE_LAB.camera.yaw);await page.keyboard.press('ArrowRight');check('Keyboard orbit and focus are visible',await page.evaluate(y=>CANDIDATE_LAB.camera.yaw>y&&getComputedStyle(document.activeElement).outlineStyle!=='none',yaw));await page.keyboard.press('Home');check('Home restores camera preset',await page.evaluate(()=>CANDIDATE_LAB.camera.distance===7.4&&CANDIDATE_LAB.camera.yaw===.36));
  await page.locator('#light').selectOption('overcast');check('Shared daylight changes rendering',await difference(textured,await shot('etched-daylight'))>2);await page.locator('#layout').selectOption('all');
  const pending=page.waitForEvent('download');await page.locator('#export').click();const download=await pending;await download.saveAs(resolve(out,'export.png'));const exportMeta=await sharp(resolve(out,'export.png')).metadata();check('Comparison export contains real PNG pixels',exportMeta.width>1000&&exportMeta.height>=800);
  const zip=page.waitForEvent('download');await page.locator('a[download]').click();const archiveDownload=await zip;await archiveDownload.saveAs(resolve(out,'hard-cel-v1.zip'));check('Saved candidate archive downloads exact bytes',createHash('sha256').update(readFileSync(resolve(out,'hard-cel-v1.zip'))).digest('hex')===createHash('sha256').update(readFileSync('art-candidates/hard-cel-v1.zip')).digest('hex'));
  for(const width of [375,768,1280]){await page.setViewportSize({width,height:960});await settle();const layout=await page.evaluate(()=>({body:document.documentElement.scrollWidth,controls:[...document.querySelectorAll('button,select')].filter(b=>b.offsetParent).map(b=>({text:b.textContent,width:b.clientWidth,scroll:b.scrollWidth,height:b.getBoundingClientRect().height})),views:[...document.querySelectorAll('.viewport')].filter(p=>!p.hidden).map(p=>({w:p.clientWidth,h:p.clientHeight}))}));check('Four-version responsive layout '+width,layout.body<=width&&layout.controls.every(c=>c.scroll<=c.width+1&&c.height>=44)&&layout.views.every(v=>v.w>300&&v.h>=380),layout);await page.screenshot({path:resolve(out,'layout-'+width+'.png'),fullPage:true});}
  await page.setViewportSize({width:1600,height:1100});await page.locator('[data-view="valley"]').click();await page.locator('#light').selectOption('golden');await page.locator('#motion').click();await page.waitForTimeout(1800);const timing=await page.evaluate(()=>{const a=CANDIDATE_LAB.timings.slice(25).sort((a,b)=>a-b);return {samples:a.length,median:a[Math.floor(a.length*.5)],p95:a[Math.floor(a.length*.95)],metrics:CANDIDATE_LAB.metrics};});check('Four animated renders sustain desktop frames',timing.samples>50&&timing.p95<100,{...timing,backend:initial.backend});await page.locator('#motion').click();await settle();const still=await page.evaluate(()=>({time:CANDIDATE_LAB.time,frames:CANDIDATE_LAB.metrics.frames}));await page.waitForTimeout(150);check('Pause stops simulation and idle draws',await page.evaluate(s=>CANDIDATE_LAB.time===s.time&&CANDIDATE_LAB.metrics.frames===s.frames,still));
  for(const view of ['commander','tower','enemy','valley']){await page.locator(`[data-view="${view}"]`).click();await settle();}const warm=await page.evaluate(()=>CANDIDATE_LAB.metrics);for(let n=0;n<2;n++)for(const view of ['commander','tower','enemy','valley']){await page.locator(`[data-view="${view}"]`).click();await settle();}check('Repeated views do not grow geometry or texture allocation',await page.evaluate(m=>CANDIDATE_LAB.metrics.geometries===m.geometries&&CANDIDATE_LAB.metrics.textures===m.textures,warm),warm);
  check('Comparison does not modify game saves',await page.evaluate(s=>JSON.stringify(localStorage)===s,initial.storage));await page.evaluate(()=>{const gl=document.querySelector('canvas').getContext('webgl2');window.recovery=gl.getExtension('WEBGL_lose_context');window.recovery.loseContext();});await page.waitForTimeout(100);check('Graphics loss shows guidance and disables export',await page.locator('#loading').isVisible()&&await page.locator('#export').isDisabled());await page.evaluate(()=>window.recovery.restoreContext());await page.waitForTimeout(500);check('Context restoration renders all versions',await page.locator('#loading').isHidden()&&!await page.locator('#export').isDisabled());
  await page.goto(base+'/hard-cel-lab.html?version=v4&layout=pair&view=tower&light=overcast');await page.waitForFunction(()=>window.CANDIDATE_LAB?.ready,null,{timeout:60000});check('Version-specific URL restores the full comparison',await page.evaluate(()=>CANDIDATE_LAB.state.version==='v4'&&CANDIDATE_LAB.state.layout==='pair'&&CANDIDATE_LAB.state.view==='tower'&&CANDIDATE_LAB.state.light==='overcast'));await page.screenshot({path:resolve(out,'desktop.png'),fullPage:true});
  const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,reducedMotion:'reduce'}),mobile=await touch.newPage();mobile.on('pageerror',e=>errors.push(String(e)));await mobile.goto(base+'/hard-cel-lab.html?layout=single');await mobile.waitForFunction(()=>window.CANDIDATE_LAB?.ready,null,{timeout:60000});await mobile.locator('button[data-version="v4"]').tap();await mobile.locator('[data-view="enemy"]').tap();check('Touch selects a version and model',await mobile.evaluate(()=>CANDIDATE_LAB.state.version==='v4'&&CANDIDATE_LAB.state.view==='enemy'));check('Reduced motion initializes a still scene',await mobile.evaluate(()=>!CANDIDATE_LAB.state.motion));await mobile.locator('.viewport:visible').scrollIntoViewIfNeeded();const y0=await mobile.evaluate(()=>CANDIDATE_LAB.camera.yaw),bounds=await mobile.locator('.viewport:visible').boundingBox(),cdp=await touch.newCDPSession(mobile),x=bounds.x+bounds.width*.4,y=Math.max(100,Math.min(650,bounds.y+200));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+65,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('Real touch swipe orbits the selected version',await mobile.evaluate(n=>CANDIDATE_LAB.camera.yaw!==n,y0));await mobile.screenshot({path:resolve(out,'touch.png'),fullPage:true});await touch.close();
  const failure=await browser.newPage();await failure.route('**/art-candidates/hard-cel-v1/lib/painted/commander.gltf',r=>r.abort());await failure.goto(base+'/hard-cel-lab.html');await failure.waitForFunction(()=>window.CANDIDATE_LAB_ERROR);check('Missing archived model shows recovery guidance and disables export',await failure.locator('#loading').isVisible()&&await failure.locator('#export').isDisabled());await failure.close();
  await page.goto(base+'/painted-lab.html');await page.locator('a[href="hard-cel-lab.html"]').click();await page.waitForFunction(()=>window.CANDIDATE_LAB?.ready,null,{timeout:60000});check('Previous study links to the candidate comparison',page.url().includes('/hard-cel-lab.html'));
  check('No runtime or shader errors',errors.length===0,errors);
}
