import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {AUDIO_CUES} from '../js/audio-catalogue.js';
import {renderCue,RATE} from './audio/design.mjs';
mkdirSync('audio',{recursive:true});mkdirSync('artifacts/audio-revamp/originals',{recursive:true});
const chunks=[],bank={};let offset=0;
for(const cue of Object.values(AUDIO_CUES)){
  bank[cue.key]=[];
  const count=['ambience','weather','reward'].includes(cue.family)?1:['ability','ui'].includes(cue.family)?2:3;
  for(let variant=0;variant<count;variant++){
    const samples=renderCue(cue.key,cue.family,variant);
    bank[cue.key].push({start:offset/RATE,duration:samples.length/RATE});chunks.push(samples,new Float32Array(RATE*.1));offset+=samples.length+RATE*.1;
  }
}
const wav=Buffer.alloc(44+offset*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(RATE,24);wav.writeUInt32LE(RATE*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(offset*2,40);
let cursor=44;for(const chunk of chunks)for(const v of chunk){wav.writeInt16LE(Math.round(Math.max(-1,Math.min(1,v))*32767),cursor);cursor+=2;}
const original='artifacts/audio-revamp/originals/feedback-bank.wav';writeFileSync(original,wav);
execFileSync('ffmpeg',['-y','-v','error','-i',original,'-c:a','libmp3lame','-b:a','128k','-write_xing','1','audio/feedback-bank.mp3']);
const data=readFileSync('audio/feedback-bank.mp3'),hash=createHash('sha256').update(data).digest('hex');
writeFileSync('js/audio-bank.js',`// Generated by tools/audio-build.mjs. Authored nonvocal sound design.\nexport const AUDIO_BANK=${JSON.stringify({file:'feedback-bank.mp3',sha256:hash,bytes:data.length,sampleRate:RATE,duration:offset/RATE,cues:bank})};\n`);
writeFileSync('audio/README.md','# Worldheart audio assets\n\nfeedback-bank.mp3: original nonvocal sound design by Codex for Worldheart,\nreproducible with node tools/audio-build.mjs and FFmpeg (libmp3lame).\nNo recordings, speech or third-party samples. Source: tools/audio/design.mjs.\n\nMusic provenance and the YuE2 model restriction are recorded separately.\n');
console.log(JSON.stringify({cues:Object.keys(bank).length,variants:Object.values(bank).flat().length,seconds:offset/RATE,bytes:data.length,sha256:hash}));
