import {createRequire} from 'node:module';import {mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';
const require=createRequire(resolve(process.env.WH_NODE_MODULES,'package.json')),{chromium}=require('playwright'),base=process.env.WH_BASE_URL||'http://127.0.0.1:8139',out=resolve(process.argv[2]||'artifacts/expedition/lobby');mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900}}),results=[],errors=[];page.on('pageerror',e=>errors.push(e.stack));page.setDefaultTimeout(180000);const ck=(name,ok,detail)=>results.push({name,ok:!!ok,detail});
try{
 await page.goto(base+'/');await page.waitForFunction(()=>window.LOBBY);ck('Default entry opens preparation lobby',page.url().includes('lobby.html'));await page.waitForTimeout(500);await page.screenshot({path:resolve(out,'courtyard.png')});
 const before=await page.evaluate(()=>LOBBY.player.toArray());await page.locator('canvas').focus();await page.keyboard.down('w');await page.waitForTimeout(500);await page.keyboard.up('w');const after=await page.evaluate(()=>LOBBY.player.toArray());ck('WASD walks through courtyard',Math.hypot(after[0]-before[0],after[2]-before[2])>1,{before,after});
 const yaw=await page.evaluate(()=>LOBBY.view.yaw);await page.mouse.move(700,500);await page.mouse.down({button:'right'});await page.mouse.move(820,500,{steps:12});await page.mouse.up({button:'right'});ck('Right drag rotates courtyard view',await page.evaluate(()=>LOBBY.view.yaw)!==yaw);
 await page.getByRole('button',{name:'Commanders',exact:true}).click();await page.getByRole('button',{name:/Longsight Precise/}).click();await page.waitForTimeout(250);await page.screenshot({path:resolve(out,'commanders.png')});await page.getByRole('button',{name:'Close station'}).click();await page.keyboard.press('e');ck('E reopens a station approached on foot',await page.locator('#station-title').textContent()==='Commanders');
 await page.getByRole('button',{name:'Mounts',exact:true}).click();await page.getByRole('button',{name:/Scout Saucer Hold/}).click();await page.getByRole('button',{name:'Tower foundry',exact:true}).click();ck('Foundry refuses unaffordable roll',await page.locator('#roll-tower').isDisabled());
 // Inject earned coins only to exercise the actual transaction/UI, not earning balance.
 await page.evaluate(async()=>{const {campaignStore}=await import(new URL('js/modes/campaign-store.js',location.href));campaignStore.commit(s=>{s.account.coins=120;return true;});});await page.reload();await page.waitForFunction(()=>window.LOBBY);ck('Commander and mount choices survive reload',await page.evaluate(()=>LOBBY.selected.commander==='marksman'&&LOBBY.selected.mount==='skyray'));
 await page.getByRole('button',{name:'Tower foundry',exact:true}).click();const p0=await page.evaluate(()=>LOBBY.profile);await page.locator('#roll-tower').click();const p1=await page.evaluate(()=>LOBBY.profile),newTower=p1.towers.find(x=>!p0.towers.includes(x));ck('Roll charges once and unlocks a new tower',p1.coins===60&&p1.towers.length===p0.towers.length+1&&!!newTower,{before:p0,after:p1});await page.locator(`[data-tower="${newTower}"]`).click();ck('Discovered tower can become opening loadout',await page.evaluate(()=>LOBBY.profile.loadout)===newTower);await page.waitForTimeout(300);await page.screenshot({path:resolve(out,'foundry.png')});
 await page.getByRole('button',{name:'Mission gate',exact:true}).click();await page.locator('#launch').click();await page.waitForFunction(()=>window.WH?.mode99&&document.querySelector('#boot.done'));ck('Launch uses chosen commander mount and opening card',await page.evaluate(key=>WH.mode99.commander.typeKey==='marksman'&&WH.mode99.mounts.choice==='skyray'&&WH.mode99.run.getHand()[0]===key,newTower));await page.locator('#btn-begin').click();await page.waitForTimeout(300);await page.screenshot({path:resolve(out,'launched.png')});
 ck('Expedition controls sit below the base upgrade without overlap',await page.evaluate(()=>document.getElementById('heart-panel').getBoundingClientRect().bottom<=document.getElementById('expedition-tools').getBoundingClientRect().top));
 await page.goto(base+'/lobby.html');await page.waitForFunction(()=>window.LOBBY);await page.getByRole('button',{name:'Commanders',exact:true}).click();await page.locator('[data-commander="duelist"]').click();await page.getByRole('button',{name:'Mission gate',exact:true}).click();ck('Existing expedition cannot silently switch commander',await page.locator('#launch').isDisabled());await page.locator('#fresh-expedition').check();ck('Explicit fresh expedition permits new commander',await page.locator('#launch').isEnabled());
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Tower foundry',exact:true}).click();await page.waitForTimeout(300);ck('Phone-width station fits viewport without horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.getElementById('station-panel').getBoundingClientRect().right<=innerWidth));await page.screenshot({path:resolve(out,'mobile.png')});
}catch(e){errors.push(String(e));await page.screenshot({path:resolve(out,'error.png')}).catch(()=>{});}finally{writeFileSync(resolve(out,'report.json'),JSON.stringify({scope:'Real lobby input, choices, reload and launch. Earned coin balance injected for the purchase fixture.',base,results,errors},null,2));console.log(JSON.stringify({passed:results.filter(x=>x.ok).length,total:results.length,failed:results.filter(x=>!x.ok),errors}));await browser.close();}if(results.some(x=>!x.ok)||errors.length)process.exitCode=1;
