// Native rendered weather transition: triggered placement, real input/frames.
import {createRequire} from 'node:module';import {mkdirSync,writeFileSync} from 'node:fs';import {resolve} from 'node:path';
const require=createRequire(resolve(process.env.WH_NODE_MODULES,'package.json')),{chromium}=require('playwright'),base=process.env.WH_BASE_URL||'http://127.0.0.1:8139',out=resolve(process.argv[2]||'artifacts/expedition/weather');mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.stack));page.setDefaultTimeout(180000);let report={};
try{
 await page.goto(base+'/?map=ninetynine&campaign=0&seed=12345');await page.waitForFunction(()=>window.WH?.mode99&&document.querySelector('#boot.done'));await page.locator('#btn-begin').click();
 await page.evaluate(()=>{WH.waves.canRaid=()=>false;WH.give(2000);for(let i=0;i<3;i++)WH.mode99.upgradeHeart();WH.rig.cancelFlight();WH.rig.dist=WH.rig.targetDist=60;document.querySelector('#expedition-tools').open=true;});
 await page.waitForTimeout(300);await page.screenshot({path:resolve(out,'before.png')});
 await page.evaluate(async()=>{const T=await import(new URL('lib/three.module.min.js',location.href)),W=WH,m=W.mode99,dir=m.commander.dir.clone().addScaledVector(m.commander.fwd,28/240).normalize();m.weather.trigger('quake',dir);m.weather.remaining=.05;window.__weatherFrames=[];window.__weatherSlices=[];window.__weatherSim=W.enemies.time;window.__weatherFocus=[W.rig.lon,W.rig.lat];const advance=m.weather.advanceShift.bind(m.weather);m.weather.advanceShift=function(){const t=performance.now();advance();__weatherSlices.push(performance.now()-t);};let last=performance.now();function frame(now){__weatherFrames.push(now-last);last=now;if(m.weather.phase!=='calm')requestAnimationFrame(frame);}requestAnimationFrame(frame);});
 await page.waitForFunction(()=>WH.game.terrainBusy);await page.evaluate(()=>WH.game.toggleBuildCard(0));await page.mouse.move(810,440);await page.locator('canvas').first().focus();await page.keyboard.down('ArrowRight');await page.waitForTimeout(160);await page.keyboard.up('ArrowRight');await page.screenshot({path:resolve(out,'shifting.png')});await page.waitForFunction(()=>!WH.game.terrainBusy);await page.evaluate(()=>WH.game.cancelBuild());await page.waitForTimeout(250);await page.screenshot({path:resolve(out,'after.png')});
 report=await page.evaluate(()=>{const sorted=__weatherFrames.slice().sort((a,b)=>a-b),p=x=>sorted[Math.min(sorted.length-1,Math.floor(sorted.length*x))];return{scope:'Native browser frames during a triggered quake; fixture gold funds three base upgrades for visible terrain.',event:WH.mode99.weather.events.at(-1),frameMs:{p50:p(.5),p95:p(.95),p99:p(.99),max:sorted.at(-1)},maxWorkSlice:Math.max(...__weatherSlices),frames:sorted.length,finiteCamera:WH.rig.camera.matrixWorld.elements.every(Number.isFinite),cameraMoved:Math.abs(WH.rig.lon-__weatherFocus[0])+Math.abs(WH.rig.lat-__weatherFocus[1])>1e-6,simulationResumed:WH.enemies.time>__weatherSim};});
 await page.evaluate(()=>{const m=WH.mode99;m.weather.trigger('tornado',m.commander.dir);m.weather.remaining=.05;});await page.waitForFunction(()=>WH.mode99.commander.weatherLift>1);await page.screenshot({path:resolve(out,'tornado.png')});report.tornadoLift=await page.evaluate(()=>WH.mode99.commander.weatherLift);
}catch(e){errors.push(String(e));}finally{report.errors=errors;report.pass=!!report.event?.vertices&&report.frames>10&&report.finiteCamera&&report.cameraMoved&&report.simulationResumed&&report.maxWorkSlice<55&&report.tornadoLift>1&&!errors.length;writeFileSync(resolve(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();}if(!report.pass)process.exitCode=1;
